import type { KeywordCueLevel } from "./keyword-cue-types.ts";

export interface KeywordCueSkillFocusEntry {
  readonly operators?: readonly string[];
  readonly cueIds?: readonly string[];
  readonly notes?: string;
  readonly levels?: readonly KeywordCueLevel[];
}

export const keywordCueSkillFocusMap: Record<
  string,
  KeywordCueSkillFocusEntry
> = {
  inversion: {
    operators: [
      "no sooner ... than",
      "hardly ... when",
      "little did",
      "only when",
      "under no circumstances",
      "not until",
    ],
    levels: ["C1", "C2"],
    cueIds: [
      "C1_SCARCELY_SCARCELY_HAD_THEY_LEFT",
      "C1_HARDLY_HARDLY_HAD_WE_ARRIVED",
      "C1_SOONER_NO_SOONER_HAD_THEY",
      "C1_LITTLE_LITTLE_DID_HE_KNOW",
      "C1_ONLY_ONLY_WHEN_SHE_ARRIVED",
      "C1_UNDER_UNDER_NO_CIRCUMSTANCES",
      "C1_RARELY_RARELY_DO_WE_SEE",
      "C1_NEVER_NEVER_HAVE_I_FELT",
      "C2_SOONER_NO_SOONER_HAD_THEY",
      "C2_HARDLY_HARDLY_HAD_SHE_ARRIVED",
      "C2_CIRCUMSTANCES_UNDER_NO_CIRCUMSTANCES",
      "C2_LITTLE_LITTLE_DID_THEY_IMAGINE",
      "C2_NOWHERE_NOWHERE_WAS_THE_REPORT",
      "C2_ONLY_ONLY_WHEN_THE_RAIN",
      "C2_SCARCELY_SCARCELY_HAD_THE_DOORS",
    ],
  },
  "reported-speech": {
    operators: [
      "is said to",
      "was told to",
      "is alleged to have",
      "was warned to",
      "is believed to have",
      "was promised that",
      "be told to",
      "be warned not to",
      "be advised to",
      "be ordered to",
      "be asked to",
      "be invited to",
      "be allowed to",
    ],
    levels: ["B2", "C1"],
    cueIds: [
      "B2_WARNED_WARNED_NOT_TO",
      "B2_ADVISED_ADVISED_TO",
      "B2_TOLD_TOLD_TO",
      "B2_ORDERED_ORDERED_TO",
      "B2_ASKED_ASKED_TO",
      "B2_INVITED_INVITED_TO",
      "B2_ALLOWED_ALLOWED_TO",
      "C1_ALLEGED_IS_ALLEGED_TO_HAVE",
      "C1_BELIEVED_IS_BELIEVED_TO_HAVE",
      "C1_SAID_IS_SAID_TO_HAVE",
      "C1_REPORTED_IS_REPORTED_TO_HAVE",
      "C1_THOUGHT_WAS_THOUGHT_TO_BE",
      "C1_UNDERSTOOD_IS_UNDERSTOOD_TO_HAVE",
      "C1_RUMOURED_IS_RUMOURED_TO_BE",
      "C1_SUPPOSED_IS_SUPPOSED_TO_HAVE",
    ],
  },
  modality: {
    operators: [
      "had better",
      "would rather",
      "ought to have",
      "must have",
      "can't have been",
      "might have to",
      "needn't have",
      "be supposed to",
    ],
    levels: ["B2", "C1", "C2"],
    cueIds: [
      "B2_BETTER_HAD_BETTER",
      "B2_WISH_WISH_I_COULD",
      "B2_NEED_NEED_NOT_HAVE_WAITED",
      "B2_NEED_NEED_TO",
      "B2_WANT_WANT_TO",
      "B2_TRY_TRY_TO",
      "B2_MEAN_NOT_MEAN_TO",
      "B2_MEANT_MEANT_TO_STOP",
      "C1_RATHER_WOULD_RATHER_YOU",
      "C1_SHOULD_SHOULD_HAVE_TOLD_ME",
      "C1_OUGHT_OUGHT_TO_HAVE_WARNED",
      "C1_MIGHT_MIGHT_HAVE_FORGOTTEN_TO",
      "C1_COULD_COULD_HAVE_BEEN_AVOIDED",
      "C1_CANT_CANT_HAVE_BEEN_PLEASED",
      "C1_MUST_MUST_HAVE_BEEN_EXHAUSTED",
      "C1_ESSENTIAL_IT_IS_ESSENTIAL_THAT",
      "C1_ADVISABLE_IT_IS_ADVISABLE_TO",
      "C2_SHOULD_SHOULD_YOU_REQUIRE_FURTHER",
      "C2_HAPPEN_SHOULD_IT_HAPPEN_THAT",
      "C2_LEST_LEST_THEY_SHOULD_FAIL",
      "C2_ACCOUNT_ON_NO_ACCOUNT_MUST",
      "C2_LONG_SO_LONG_AS_YOU",
      "C2_WERE_WERE_IT_NOT_FOR",
      "C2_HAD_HAD_IT_NOT_BEEN",
    ],
  },
  comparatives: {
    operators: [
      "not as ... as",
      "the same as",
      "twice as ... as",
      "far more ... than",
      "nowhere near as ... as",
      "no longer as ... as",
    ],
    levels: ["B2", "C1"],
    cueIds: [
      "B2_AS_AS_AS",
      "B2_MORE_MORE_THAN",
      "B2_LESS_LESS_THAN",
      "B2_SAME_THE_SAME_AS",
      "B2_FAR_FAR_TOO",
      "B2_JUST_JUST_AS",
    ],
  },
  conditionals: {
    operators: [
      "if it hadn't been for",
      "in case",
      "provided that",
      "as long as",
      "on condition that",
      "unless",
      "were it not for",
      "only if",
    ],
    levels: ["B2", "C1", "C2"],
    cueIds: [
      "C1_CASE_IN_CASE",
      "B2_CASE_IN_CASE_OF_RAIN",
      "B2_PROVIDED_PROVIDED_THAT_YOU_BRING",
      "B2_UNLESS_UNLESS_THEY_CALL",
      "B2_LONG_AS_LONG_AS_WE_PLAN",
      "B2_CONDITION_ON_CONDITION_THAT_YOU_PAY",
      "B2_ONLY_ONLY_IF_YOU_CONFIRM",
      "C1_CALL_CALL_THE_MEETING_OFF",
      "C1_STILL_WOULD_STILL_BE_LOOKING",
      "C1_MISSED_HAD_MISSED_HER_FLIGHT",
      "C1_ONLY_ONLY_WHEN_SHE_ARRIVED",
      "C1_NEVER_NEVER_HAVE_I_FELT",
      "C1_UNDER_UNDER_NO_CIRCUMSTANCES",
      "C2_HAD_HAD_IT_NOT_BEEN",
      "C2_WERE_WERE_IT_NOT_FOR",
      "C2_WHATEVER_WHATEVER_HAPPENS_YOU_MUST",
      "C2_ASSUMING_ASSUMING_THAT_THIS_HOLDS",
      "C2_PROVIDED_PROVIDED_THAT_YOU_REMAIN",
      "C2_LEST_LEST_THEY_SHOULD_FAIL",
    ],
  },
};
