import type { KeywordCue, KeywordCueLevel } from "./keyword-cue-types.ts";

interface KeywordCueDescriptor {
  readonly id: string;
  readonly keyword: string;
  readonly operator: string;
  readonly frames: string | readonly string[];
  readonly variants: readonly string[];
  readonly notes?: string;
}

function toArray<T>(value: T | readonly T[]): readonly T[] {
  if (Array.isArray(value)) {
    return value.slice() as readonly T[];
  }
  return [value] as readonly T[];
}

function normaliseFrame(rawFrame: string): string {
  const trimmed = rawFrame.trim();
  if (!trimmed.includes("{{gap}}")) {
    throw new Error(`Frame "${rawFrame}" must include the placeholder {{gap}}`);
  }
  return trimmed.replace(/{{gap}}/g, "_______");
}

function createCue(
  level: KeywordCueLevel,
  descriptor: KeywordCueDescriptor,
): KeywordCue {
  const frames = toArray(descriptor.frames).map(normaliseFrame);
  return {
    id: descriptor.id,
    keyword: descriptor.keyword.trim().toUpperCase(),
    operator: descriptor.operator,
    frames,
    variants: toArray(descriptor.variants).map((variant) => variant.trim()),
    notes: descriptor.notes,
    level,
  };
}

const B2_CUE_DESCRIPTORS: readonly KeywordCueDescriptor[] = [
  {
    id: "B2_NOTICE_TAKE_NOTICE_OF",
    keyword: "NOTICE",
    operator: "take notice of",
    frames: "take {{gap}} of the warnings",
    variants: ["ANY NOTICE", "MUCH NOTICE"],
    notes: "Encourage attention to signage; draw from B2 handbook examples.",
  },
  {
    id: "B2_POINT_NO_POINT_IN",
    keyword: "POINT",
    operator: "there is no point in",
    frames: "there {{gap}} in",
    variants: ["IS NO POINT", "WAS NO POINT"],
    notes: "Classic futility paraphrase with gerund requirement.",
  },
  {
    id: "B2_DUE_DUE_TO",
    keyword: "DUE",
    operator: "due to",
    frames: "was {{gap}} heavy traffic",
    variants: ["DUE TO", "DUE TO THE"],
    notes: "Causal connective enforcing preposition retention.",
  },
  {
    id: "B2_FORWARD_LOOK_FORWARD_TO",
    keyword: "FORWARD",
    operator: "look forward to",
    frames: "looking {{gap}} seeing",
    variants: ["FORWARD TO"],
    notes: "Topic rotation cue favouring positive anticipation tone.",
  },
  {
    id: "B2_WISH_WISH_I_COULD",
    keyword: "WISH",
    operator: "wish + past/could",
    frames: "I {{gap}} join you today",
    variants: ["WISH I COULD"],
    notes:
      "Counterfactual desire requiring the modal past; keep the keyword unchanged.",
  },
  {
    id: "B2_SOLD_BE_SOLD_OUT_OF",
    keyword: "SOLD",
    operator: "be sold out of",
    frames: "was {{gap}} tickets within hours",
    variants: ["SOLD OUT OF", "SOLD OUT OF THE"],
    notes: "Highlights depleted stock phrasing with passive voice.",
  },
  {
    id: "B2_MEAN_NOT_MEAN_TO",
    keyword: "MEAN",
    operator: "not mean to + verb",
    frames: "didn't {{gap}} upset you",
    variants: ["MEAN TO"],
    notes: 'Negative intention cue; frame supplies the auxiliary "didn\'t".',
  },
  {
    id: "B2_ONLY_ONLY_WHEN_WE_ARRIVED",
    keyword: "ONLY",
    operator: "only when",
    frames: "The last train left {{gap}} we arrived",
    variants: ["ONLY WHEN WE HAD ARRIVED", "ONLY WHEN THEY HAD ARRIVED"],
    notes:
      "Time-link trigger that keeps the clause after the blank; mirrors B2 exam rubrics.",
  },
  {
    id: "B2_SOON_AS_SOON_AS_THEY_CONFIRM",
    keyword: "SOON",
    operator: "as soon as",
    frames: "We will start organising the conference {{gap}} their support",
    variants: ["AS SOON AS THEY CONFIRM", "AS SOON AS YOU CONFIRM"],
    notes:
      "Sequential trigger ensuring the subordinate clause follows the blank.",
  },
  {
    id: "B2_BEEN_TO_HAVE_BEEN_DESIGNED",
    keyword: "BEEN",
    operator: "to have been + Vpp",
    frames: "The museum is thought {{gap}} by a renowned architect",
    variants: ["TO HAVE BEEN DESIGNED", "TO HAVE BEEN BUILT"],
    notes:
      "Reporting passive structure often tested at B2; keep perfect infinitive inside the gap.",
  },
  {
    id: "B2_TAKE_TAKES_HALF_AN_HOUR",
    keyword: "TAKES",
    operator: "it takes + time",
    frames: "It {{gap}} to reach the venue",
    variants: ["TAKES HALF AN HOUR", "TAKES THIRTY MINUTES"],
    notes: 'Impersonal time expressions must retain "It" outside the blank.',
  },
  {
    id: "B2_ABLE_ABLE_TO_REACH",
    keyword: "ABLE",
    operator: "be able to + verb",
    frames: "We were not {{gap}} the summit before sunset",
    variants: ["ABLE TO REACH"],
    notes:
      "Simple modal paraphrase keeping the negative auxiliary outside the blank.",
  },
  {
    id: "B2_USED_BE_USED_TO",
    keyword: "USED",
    operator: "be used to + gerund",
    frames: "is {{gap}} up",
    variants: ["USED TO GETTING"],
    notes: "Highlights noun/gerund collocation with “used to”.",
  },
  {
    id: "B2_HABIT_HAVE_A_HABIT_OF",
    keyword: "HABIT",
    operator: "have a habit of",
    frames: "{{gap}} leaving",
    variants: ["HAS A HABIT OF"],
  },
  {
    id: "B2_WARNED_WARNED_NOT_TO",
    keyword: "WARNED",
    operator: "be warned not to",
    frames: "were {{gap}} run",
    variants: ["WARNED NOT TO"],
  },
  {
    id: "B2_ADVISED_ADVISED_TO",
    keyword: "ADVISED",
    operator: "be advised to",
    frames: "were {{gap}} rest",
    variants: ["ADVISED TO"],
  },
  {
    id: "B2_TOLD_TOLD_TO",
    keyword: "TOLD",
    operator: "be told to",
    frames: "were {{gap}} leave",
    variants: ["TOLD TO"],
  },
  {
    id: "B2_ORDERED_ORDERED_TO",
    keyword: "ORDERED",
    operator: "be ordered to",
    frames: "were {{gap}} stay",
    variants: ["ORDERED TO"],
  },
  {
    id: "B2_ASKED_ASKED_TO",
    keyword: "ASKED",
    operator: "be asked to",
    frames: "were {{gap}} help",
    variants: ["ASKED TO"],
  },
  {
    id: "B2_INVITED_INVITED_TO",
    keyword: "INVITED",
    operator: "be invited to",
    frames: "was {{gap}} join",
    variants: ["INVITED TO"],
  },
  {
    id: "B2_ALLOWED_ALLOWED_TO",
    keyword: "ALLOWED",
    operator: "be allowed to",
    frames: "are {{gap}} use",
    variants: ["ALLOWED TO"],
  },
  {
    id: "B2_FORBIDDEN_FORBIDDEN_TO",
    keyword: "FORBIDDEN",
    operator: "be forbidden to",
    frames: "were {{gap}} enter",
    variants: ["FORBIDDEN TO"],
  },
  {
    id: "B2_PREVENTED_PREVENTED_FROM",
    keyword: "PREVENTED",
    operator: "be prevented from",
    frames: "was {{gap}} leaving",
    variants: ["PREVENTED FROM"],
  },
  {
    id: "B2_ACCUSED_ACCUSED_OF",
    keyword: "ACCUSED",
    operator: "be accused of",
    frames: "was {{gap}} cheating",
    variants: ["ACCUSED OF"],
  },
  {
    id: "B2_INSISTED_INSISTED_ON",
    keyword: "INSISTED",
    operator: "insist on",
    frames: "She {{gap}} for the meal",
    variants: ["INSISTED ON PAYING"],
  },
  {
    id: "B2_DENIED_DENIED_VING",
    keyword: "DENIED",
    operator: "deny + gerund",
    frames: "He {{gap}} the blame",
    variants: ["DENIED TAKING"],
  },
  {
    id: "B2_PERSUADED_PERSUADED_TO",
    keyword: "PERSUADED",
    operator: "be persuaded to",
    frames: "was {{gap}} sign",
    variants: ["PERSUADED TO"],
  },
  {
    id: "B2_ENCOURAGED_ENCOURAGED_TO",
    keyword: "ENCOURAGED",
    operator: "be encouraged to",
    frames: "was {{gap}} apply",
    variants: ["ENCOURAGED TO"],
  },
  {
    id: "B2_OFFERED_OFFERED_TO",
    keyword: "OFFERED",
    operator: "offer to",
    frames: "He {{gap}} help",
    variants: ["OFFERED TO"],
  },
  {
    id: "B2_PROMISED_PROMISED_TO",
    keyword: "PROMISED",
    operator: "promise to",
    frames: "She {{gap}} call",
    variants: ["PROMISED TO"],
  },
  {
    id: "B2_DECIDED_DECIDED_TO",
    keyword: "DECIDED",
    operator: "decide to",
    frames: "They {{gap}} leave",
    variants: ["DECIDED TO"],
  },
  {
    id: "B2_AGREED_AGREED_TO",
    keyword: "AGREED",
    operator: "agree to",
    frames: "They {{gap}} share",
    variants: ["AGREED TO"],
  },
  {
    id: "B2_MANAGED_MANAGED_TO",
    keyword: "MANAGED",
    operator: "manage to",
    frames: "She {{gap}} finish",
    variants: ["MANAGED TO"],
  },
  {
    id: "B2_AWARE_AWARE_OF",
    keyword: "AWARE",
    operator: "be aware of",
    frames: "is {{gap}} the",
    variants: ["AWARE OF"],
  },
  {
    id: "B2_INTERESTED_INTERESTED_IN",
    keyword: "INTERESTED",
    operator: "be interested in",
    frames: "is {{gap}} joining",
    variants: ["INTERESTED IN"],
  },
  {
    id: "B2_KEEN_KEEN_ON",
    keyword: "KEEN",
    operator: "be keen on",
    frames: "is {{gap}} taking",
    variants: ["KEEN ON"],
  },
  {
    id: "B2_FOND_FOND_OF",
    keyword: "FOND",
    operator: "be fond of",
    frames: "is {{gap}} reading",
    variants: ["FOND OF"],
  },
  {
    id: "B2_GOOD_GOOD_AT",
    keyword: "GOOD",
    operator: "be good at",
    frames: "is {{gap}} solving",
    variants: ["GOOD AT"],
  },
  {
    id: "B2_BAD_BAD_AT",
    keyword: "BAD",
    operator: "be bad at",
    frames: "is {{gap}} remembering",
    variants: ["BAD AT"],
  },
  {
    id: "B2_BETTER_HAD_BETTER",
    keyword: "BETTER",
    operator: "had better",
    frames: "You {{gap}} leave",
    variants: ["HAD BETTER"],
    notes: "Modal advice cue; ensures invariant “had better”.",
  },
  {
    id: "B2_SO_SO_THAT",
    keyword: "SO",
    operator: "so ... that",
    frames: "was {{gap}} that",
    variants: ["SO TIRED"],
  },
  {
    id: "B2_SUCH_SUCH_THAT",
    keyword: "SUCH",
    operator: "such ... that",
    frames: "was {{gap}} that",
    variants: ["SUCH A MESS"],
  },
  {
    id: "B2_TOO_TOO_TO",
    keyword: "TOO",
    operator: "too ... to",
    frames: "was {{gap}} to",
    variants: ["TOO HEAVY"],
  },
  {
    id: "B2_ENOUGH_ENOUGH_TO",
    keyword: "ENOUGH",
    operator: "enough ... to",
    frames: "had {{gap}} to",
    variants: ["ENOUGH MONEY"],
  },
  {
    id: "B2_AS_AS_AS",
    keyword: "AS",
    operator: "as ... as",
    frames: "not {{gap}} tall compared with",
    variants: ["AS TALL AS"],
    notes:
      "Comparative equality pattern; blank provides the repeated AS around the adjective.",
  },
  {
    id: "B2_MORE_MORE_THAN",
    keyword: "MORE",
    operator: "comparative more ... than",
    frames: "was {{gap}} than",
    variants: ["MORE INTERESTING"],
  },
  {
    id: "B2_LESS_LESS_THAN",
    keyword: "LESS",
    operator: "comparative less ... than",
    frames: "was {{gap}} than",
    variants: ["LESS EXPENSIVE"],
  },
  {
    id: "B2_SAME_THE_SAME_AS",
    keyword: "SAME",
    operator: "the same as",
    frames: "is {{gap}} as",
    variants: ["THE SAME"],
  },
  {
    id: "B2_NECESSARY_IT_IS_NECESSARY_TO",
    keyword: "NECESSARY",
    operator: "it is necessary to",
    frames: "{{gap}} submit",
    variants: ["IT IS NECESSARY TO"],
  },
  {
    id: "B2_IMPORTANT_IT_IS_IMPORTANT_TO",
    keyword: "IMPORTANT",
    operator: "it is important to",
    frames: "{{gap}} attend",
    variants: ["IT IS IMPORTANT TO"],
  },
  {
    id: "B2_POSSIBLE_IT_IS_POSSIBLE_TO",
    keyword: "POSSIBLE",
    operator: "it is possible to",
    frames: "{{gap}} solve",
    variants: ["IT IS POSSIBLE TO"],
  },
  {
    id: "B2_LIKELY_IS_LIKELY_TO",
    keyword: "LIKELY",
    operator: "is likely to",
    frames: "{{gap}} rain",
    variants: ["IS LIKELY TO"],
  },
  {
    id: "B2_UNLIKELY_IS_UNLIKELY_TO",
    keyword: "UNLIKELY",
    operator: "is unlikely to",
    frames: "{{gap}} arrive",
    variants: ["IS UNLIKELY TO"],
  },
  {
    id: "B2_CERTAIN_IS_CERTAIN_TO",
    keyword: "CERTAIN",
    operator: "is certain to",
    frames: "{{gap}} win",
    variants: ["IS CERTAIN TO"],
  },
  {
    id: "B2_SURE_IS_SURE_TO",
    keyword: "SURE",
    operator: "is sure to",
    frames: "{{gap}} be",
    variants: ["IS SURE TO"],
  },
  {
    id: "B2_BOUND_IS_BOUND_TO",
    keyword: "BOUND",
    operator: "is bound to",
    frames: "{{gap}} succeed",
    variants: ["IS BOUND TO"],
  },
  {
    id: "B2_WORTH_WORTH_VING",
    keyword: "WORTH",
    operator: "be worth + gerund",
    frames: "It is {{gap}} the proposal",
    variants: ["WORTH CONSIDERING"],
  },
  {
    id: "B2_DIFFICULT_IS_DIFFICULT_TO",
    keyword: "DIFFICULT",
    operator: "is difficult to",
    frames: "{{gap}} find",
    variants: ["IS DIFFICULT TO"],
  },
  {
    id: "B2_EASY_IS_EASY_TO",
    keyword: "EASY",
    operator: "is easy to",
    frames: "{{gap}} use",
    variants: ["IS EASY TO"],
  },
  {
    id: "B2_SAFE_IS_SAFE_TO",
    keyword: "SAFE",
    operator: "is safe to",
    frames: "{{gap}} touch",
    variants: ["IS SAFE TO"],
  },
  {
    id: "B2_DANGEROUS_IS_DANGEROUS_TO",
    keyword: "DANGEROUS",
    operator: "is dangerous to",
    frames: "{{gap}} climb",
    variants: ["IS DANGEROUS TO"],
  },
  {
    id: "B2_FUN_IS_FUN_TO",
    keyword: "FUN",
    operator: "is fun to",
    frames: "{{gap}} learn",
    variants: ["IS FUN TO"],
  },
  {
    id: "B2_FAMOUS_FAMOUS_FOR",
    keyword: "FAMOUS",
    operator: "be famous for",
    frames: "is {{gap}} its cuisine",
    variants: ["FAMOUS FOR"],
  },
  {
    id: "B2_RESPONSIBLE_RESPONSIBLE_FOR",
    keyword: "RESPONSIBLE",
    operator: "be responsible for",
    frames: "is {{gap}} organising",
    variants: ["RESPONSIBLE FOR"],
  },
  {
    id: "B2_CAPABLE_CAPABLE_OF",
    keyword: "CAPABLE",
    operator: "be capable of",
    frames: "is {{gap}} handling",
    variants: ["CAPABLE OF"],
  },
  {
    id: "B2_PROUD_PROUD_OF",
    keyword: "PROUD",
    operator: "be proud of",
    frames: "is {{gap}} winning",
    variants: ["PROUD OF"],
  },
  {
    id: "B2_SCARED_SCARED_OF",
    keyword: "SCARED",
    operator: "be scared of",
    frames: "is {{gap}} flying",
    variants: ["SCARED OF"],
  },
  {
    id: "B2_AFRAID_AFRAID_OF",
    keyword: "AFRAID",
    operator: "be afraid of",
    frames: "is {{gap}} swimming",
    variants: ["AFRAID OF"],
  },
  {
    id: "B2_TIRED_TIRED_OF",
    keyword: "TIRED",
    operator: "be tired of",
    frames: "is {{gap}} waiting",
    variants: ["TIRED OF"],
  },
  {
    id: "B2_FED_FED_UP_WITH",
    keyword: "FED",
    operator: "be fed up with",
    frames: "is {{gap}} the delays",
    variants: ["FED UP WITH"],
  },
  {
    id: "B2_SICK_SICK_OF",
    keyword: "SICK",
    operator: "be sick of",
    frames: "is {{gap}} hearing",
    variants: ["SICK OF"],
  },
  {
    id: "B2_FAR_FAR_TOO",
    keyword: "FAR",
    operator: "far too ...",
    frames: "was {{gap}} busy",
    variants: ["FAR TOO"],
  },
  {
    id: "B2_JUST_JUST_AS",
    keyword: "JUST",
    operator: "just as ... as",
    frames: "was {{gap}} exciting",
    variants: ["JUST AS"],
  },
  {
    id: "B2_EITHER_EITHER_OR",
    keyword: "EITHER",
    operator: "either ... or",
    frames: "{{gap}} tea",
    variants: ["EITHER COFFEE OR"],
  },
  {
    id: "B2_UNLESS_UNLESS_THEY_CALL",
    keyword: "UNLESS",
    operator: "unless",
    frames: ["{{gap}}, postpone the briefing"],
    variants: ["UNLESS THEY CALL US FIRST", "UNLESS THEY ARRIVE ON TIME"],
    notes:
      "Negative condition cue emphasising exception handling before progress.",
  },
  {
    id: "B2_PROVIDED_PROVIDED_THAT_YOU_BRING",
    keyword: "PROVIDED",
    operator: "provided that",
    frames: ["{{gap}}, you may enter"],
    variants: ["PROVIDED THAT YOU BRING ID", "PROVIDED THAT YOU HAVE ID"],
    notes:
      "Positive condition requiring fulfilment before allowance is granted.",
  },
  {
    id: "B2_CASE_IN_CASE_OF_RAIN",
    keyword: "CASE",
    operator: "in case",
    frames: ["{{gap}}, pack umbrellas"],
    variants: ["IN CASE OF RAIN", "IN CASE IT RAINS"],
    notes: "Preventative planning cue encouraging contingency preparation.",
  },
  {
    id: "B2_LONG_AS_LONG_AS_WE_PLAN",
    keyword: "LONG",
    operator: "as long as",
    frames: ["{{gap}}, we will stay on schedule"],
    variants: ["AS LONG AS WE START", "AS LONG AS YOU STAY"],
    notes:
      "Conditional duration cue reinforcing sustained behaviour requirements.",
  },
  {
    id: "B2_CONDITION_ON_CONDITION_THAT_YOU_PAY",
    keyword: "CONDITION",
    operator: "on condition that",
    frames: ["{{gap}}, the agreement stands"],
    variants: ["ON CONDITION THAT YOU PAY", "ON CONDITION THAT YOU SIGN"],
    notes: "Formal stipulation cue aligning with contractual obligations.",
  },
  {
    id: "B2_ONLY_ONLY_IF_YOU_CONFIRM",
    keyword: "ONLY",
    operator: "only if",
    frames: ["{{gap}}, we can proceed"],
    variants: ["ONLY IF YOU CONFIRM", "ONLY IF THEY AGREE"],
    notes: "Exclusive condition cue requiring explicit confirmation.",
  },
  {
    id: "B2_SOONER_NO_SOONER_THAN",
    keyword: "SOONER",
    operator: "no sooner ... than ...",
    frames: "{{gap}} the report than she sent it",
    variants: ["NO SOONER HAD SHE FINISHED", "NO SOONER HAD WE FINISHED"],
    notes: "Inversion trigger—keep the auxiliary before the subject.",
  },
  {
    id: "B2_LET_LET_VISITORS_ENTER",
    keyword: "LET",
    operator: "let + object + infinitive",
    frames: "We must not {{gap}} without protective clothing",
    variants: ["LET VISITORS ENTER", "LET PEOPLE ENTER"],
    notes:
      "Permission control pattern; retain the negative modal outside the gap.",
  },
  {
    id: "B2_NEED_NEED_NOT_HAVE_WAITED",
    keyword: "NEED",
    operator: "need not have + Vpp",
    frames: "You {{gap}} for me in the rain",
    variants: ["NEED NOT HAVE WAITED"],
    notes:
      "Past unnecessary action; avoid contractions to respect window counting.",
  },
  {
    id: "B2_MEANT_MEANT_TO_STOP",
    keyword: "MEANT",
    operator: "be meant to + verb",
    frames: "The instructions were {{gap}} people using the lift during alarms",
    variants: ["MEANT TO STOP"],
    notes: "Purpose expression with passive subject; keep gerund after blank.",
  },
  {
    id: "B2_RATHER_WOULD_RATHER_YOU",
    keyword: "RATHER",
    operator: "would rather + subject + past",
    frames: "I {{gap}} mention the ending",
    variants: ["WOULD RATHER YOU"],
    notes: "Preference construction requiring a following past-tense clause.",
  },
  {
    id: "B2_PLAN_PLAN_TO",
    keyword: "PLAN",
    operator: "plan to",
    frames: "They {{gap}} next summer",
    variants: ["PLAN TO TRAVEL"],
  },
  {
    id: "B2_INTEND_INTEND_TO",
    keyword: "INTEND",
    operator: "intend to",
    frames: "{{gap}} start",
    variants: ["INTEND TO"],
  },
  {
    id: "B2_EXPECT_EXPECT_TO",
    keyword: "EXPECT",
    operator: "expect to",
    frames: "{{gap}} finish",
    variants: ["EXPECT TO"],
  },
  {
    id: "B2_HOPE_HOPE_TO",
    keyword: "HOPE",
    operator: "hope to",
    frames: "{{gap}} see",
    variants: ["HOPE TO"],
  },
  {
    id: "B2_WANT_WANT_TO",
    keyword: "WANT",
    operator: "want to",
    frames: "{{gap}} visit",
    variants: ["WANT TO"],
  },
  {
    id: "B2_NEED_NEED_TO",
    keyword: "NEED",
    operator: "need to",
    frames: "{{gap}} leave",
    variants: ["NEED TO"],
  },
  {
    id: "B2_TRY_TRY_TO",
    keyword: "TRY",
    operator: "try to",
    frames: "{{gap}} arrive",
    variants: ["TRY TO"],
  },
  {
    id: "B2_REGRET_REGRET_HAVING",
    keyword: "REGRET",
    operator: "regret + perfect gerund",
    frames: "{{gap}} saying",
    variants: ["REGRET HAVING"],
  },
  {
    id: "B2_ADMIT_ADMIT_VING",
    keyword: "ADMIT",
    operator: "admit + gerund",
    frames: "They {{gap}} the mistake",
    variants: ["ADMIT BREAKING"],
  },
  {
    id: "B2_SUGGEST_SUGGEST_VING",
    keyword: "SUGGEST",
    operator: "suggest + gerund",
    frames: "They {{gap}} at noon",
    variants: ["SUGGEST MEETING"],
  },
  {
    id: "B2_RECOMMEND_RECOMMEND_VING",
    keyword: "RECOMMEND",
    operator: "recommend + gerund",
    frames: "Doctors {{gap}} regular breaks",
    variants: ["RECOMMEND TAKING"],
  },
  {
    id: "B2_AVOID_AVOID_VING",
    keyword: "AVOID",
    operator: "avoid + gerund",
    frames: "You should {{gap}} sugary snacks",
    variants: ["AVOID EATING"],
  },
  {
    id: "B2_FINISH_FINISH_VING",
    keyword: "FINISH",
    operator: "finish + gerund",
    frames: "They planned to {{gap}} it that night",
    variants: ["FINISH READING"],
  },
  {
    id: "B2_LOVE_LOVE_VING",
    keyword: "LOVE",
    operator: "love + gerund",
    frames: "They {{gap}} together",
    variants: ["LOVE TRAVELLING"],
  },
] as const;

const C1_CUE_DESCRIPTORS: readonly KeywordCueDescriptor[] = [
  {
    id: "C1_EYE_KEEP_AN_EYE_ON",
    keyword: "EYE",
    operator: "keep an eye on",
    frames: "She stayed late, {{gap}} the monitors",
    variants: ["KEEPING AN EYE ON"],
  },
  {
    id: "C1_HIGHER_BE_HIGHER_THAN",
    keyword: "HIGHER",
    operator: "tend to be higher than",
    frames: "Prices tend {{gap}} now",
    variants: ["TO BE HIGHER THAN IT IS"],
  },
  {
    id: "C1_TELL_AS_FAR_AS_I_CAN_TELL",
    keyword: "TELL",
    operator: "as far as I can tell",
    frames: "{{gap}}, the results look consistent",
    variants: ["AS FAR AS I CAN TELL"],
  },
  {
    id: "C1_FEET_PUT_MY_FEET_UP",
    keyword: "FEET",
    operator: "put my feet up",
    frames: "could {{gap}} and",
    variants: ["PUT MY FEET UP"],
  },
  {
    id: "C1_CAME_CAME_UP_WITH_THE_SUGGESTION_OF",
    keyword: "CAME",
    operator: "come up with the suggestion of",
    frames: "She {{gap}} organising the charity event",
    variants: ["CAME UP WITH THE SUGGESTION OF"],
  },
  {
    id: "C1_CASE_IN_CASE",
    keyword: "CASE",
    operator: "in case",
    frames: "Take gloves {{gap}} cold tonight",
    variants: ["IN CASE IT IS"],
  },
  {
    id: "C1_ABACK_TAKEN_ABACK_AT",
    keyword: "ABACK",
    operator: "be taken aback at",
    frames: "was {{gap}} her remarks",
    variants: ["TAKEN ABACK AT"],
  },
  {
    id: "C1_TIME_AT_THE_TIME_OF",
    keyword: "TIME",
    operator: "at the time of",
    frames: "The report was drafted {{gap}} the fire",
    variants: ["AT THE TIME OF"],
  },
  {
    id: "C1_DESPITE_DESPITE_THE_COMPANY_OFFERING",
    keyword: "DESPITE",
    operator: "despite + gerund",
    frames: "{{gap}} the new benefits package",
    variants: ["DESPITE THE COMPANY OFFERING"],
  },
  {
    id: "C1_LIFT_GIVE_HER_A_LIFT",
    keyword: "LIFT",
    operator: "give someone a lift",
    frames: "You should {{gap}} as she has no car",
    variants: ["GIVE HER A LIFT"],
  },
  {
    id: "C1_NOTICE_TAKE_ANY_NOTICE_OF",
    keyword: "NOTICE",
    operator: "take notice of",
    frames: "People rarely {{gap}} the warnings",
    variants: ["TAKE ANY NOTICE OF"],
  },
  {
    id: "C1_EXPLANATION_GIVE_A_CLEAR_EXPLANATION_OF",
    keyword: "EXPLANATION",
    operator: "give a (clear) explanation of/about",
    frames: "could {{gap}} the delays",
    variants: [
      "GIVE A CLEAR EXPLANATION OF",
      "GIVE AN EXPLANATION OF",
      "GIVE A CLEAR EXPLANATION ABOUT",
    ],
    notes: "Nominalisation device requiring explicit explanation phrasing.",
  },
  {
    id: "C1_DATES_DATES_BACK_TO",
    keyword: "DATES",
    operator: "dates back to",
    frames: "proposal {{gap}} the",
    variants: ["DATES BACK TO"],
  },
  {
    id: "C1_CANT_CANT_HAVE_BEEN_PLEASED",
    keyword: "CAN'T",
    operator: "can't have been",
    frames: "She {{gap}} hear the news",
    variants: ["CAN'T HAVE BEEN PLEASED TO"],
  },
  {
    id: "C1_EVER_HARDLY_EVER_DOES",
    keyword: "EVER",
    operator: "hardly ever",
    frames: "He {{gap}} others suggest",
    variants: ["HARDLY EVER DOES WHAT"],
  },
  {
    id: "C1_TURNED_TURNED_OUT_TO_BE",
    keyword: "TURNED",
    operator: "turn out to be",
    frames: "It {{gap}} a success",
    variants: ["TURNED OUT TO BE"],
  },
  {
    id: "C1_A_HAD_I_BEEN_IN_SUCH_A",
    keyword: "A",
    operator: "never had I been in such a",
    frames: "Never {{gap}} predicament",
    variants: ["HAD I BEEN IN SUCH A"],
  },
  {
    id: "C1_FILL_TO_FILL_THE_VACANCY",
    keyword: "FILL",
    operator: "fill the vacancy",
    frames: "They plan {{gap}} soon",
    variants: ["TO FILL THE VACANCY"],
  },
  {
    id: "C1_ACCORDANCE_IN_ACCORDANCE_WITH",
    keyword: "ACCORDANCE",
    operator: "in accordance with",
    frames: "We acted {{gap}} instructions",
    variants: ["IN ACCORDANCE WITH HIS"],
  },
  {
    id: "C1_CALL_CALL_THE_MEETING_OFF",
    keyword: "CALL",
    operator: "call the meeting off",
    frames: "{{gap}} unless absolutely necessary",
    variants: ["CALL THE MEETING OFF"],
  },
  {
    id: "C1_UP_TURNS_UP_AT_EVERY",
    keyword: "UP",
    operator: "turn up at every opportunity",
    frames: "He {{gap}} opportunity offered",
    variants: ["TURNS UP AT EVERY"],
  },
  {
    id: "C1_POPULAR_CONTRARY_TO_POPULAR_BELIEF",
    keyword: "POPULAR",
    operator: "contrary to popular belief",
    frames: "Contrary {{gap}}, the stereotype is inaccurate",
    variants: ["TO POPULAR BELIEF", "TO POPULAR OPINION"],
    notes:
      'Keep "Contrary" outside the blank so the cue supplies the full prepositional phrase.',
  },
  {
    id: "C1_DUE_IS_DUE_TO_HER",
    keyword: "DUE",
    operator: "is due to",
    frames: "Their progress {{gap}} mentoring",
    variants: ["IS DUE TO HER"],
  },
  {
    id: "C1_TAKES_DO_WHATEVER_IT_TAKES",
    keyword: "TAKES",
    operator: "do whatever/everything/anything it takes",
    frames: "will {{gap}} to secure funding",
    variants: [
      "DO WHATEVER IT TAKES",
      "DO EVERYTHING IT TAKES",
      "DO ANYTHING IT TAKES",
    ],
    notes:
      "Highlights determination idiom; allows limited determiner variation.",
  },
  {
    id: "C1_EXTENT_THE_EXTENT_OF",
    keyword: "EXTENT",
    operator: "the extent of",
    frames: "It was not {{gap}} contribution became clear",
    variants: [
      "UNTIL SHE LEFT THAT THE EXTENT",
      "UNTIL THEY LEFT THAT THE EXTENT",
    ],
    notes:
      'Cleft trigger; the blank must include "that the EXTENT" before the noun phrase that follows.',
  },
  {
    id: "C1_HARD_FOUND_IT_HARD_TO",
    keyword: "HARD",
    operator: "find it hard to",
    frames: "She {{gap}} get started",
    variants: ["FOUND IT HARD TO"],
  },
  {
    id: "C1_SUCH_SUCH_A_CONFUSING_FILM",
    keyword: "SUCH",
    operator: "such a ... that",
    frames: "It was {{gap}} that we left early",
    variants: ["SUCH A CONFUSING FILM"],
  },
  {
    id: "C1_RESULTED_RESULTED_FROM_THE",
    keyword: "RESULTED",
    operator: "resulted from",
    frames: "The strike {{gap}} disagreement over pay",
    variants: ["RESULTED FROM THE"],
  },
  {
    id: "C1_LIGHT_WITHDRAWN_IN_LIGHT_OF",
    keyword: "LIGHT",
    operator: "withdrawn in (the) light of",
    frames: "was {{gap}} the new evidence",
    variants: ["WITHDRAWN IN THE LIGHT OF", "WITHDRAWN IN LIGHT OF"],
    notes: "Formal register cue for responsive decisions.",
  },
  {
    id: "C1_EVER_SUPERLATIVE_EVER_MET",
    keyword: "EVER",
    operator: "the most ... I have ever",
    frames: "the kindest person {{gap}} before",
    variants: ["I HAVE EVER MET"],
  },
  {
    id: "C1_TERMS_COME_TO_TERMS_WITH",
    keyword: "TERMS",
    operator: "come to terms with",
    frames: "They {{gap}} the loss",
    variants: ["COME TO TERMS WITH"],
  },
  {
    id: "C1_STILL_WOULD_STILL_BE_LOOKING",
    keyword: "STILL",
    operator: "would still be",
    frames: "If it hadn't {{gap}} be searching for answers",
    variants: ["BEEN FOR THEM I WOULD STILL"],
    notes:
      "Third conditional survivor clause; add a comma after the blank if stylistically preferred.",
  },
  {
    id: "C1_PIECE_TO_PIECE_TOGETHER",
    keyword: "PIECE",
    operator: "piece together",
    frames:
      "The conflicting statements made it difficult to {{gap}} what had happened",
    variants: ["PIECE IT TOGETHER"],
    notes:
      'Keep the infinitive marker before the blank; include "it" to satisfy the C1 word window.',
  },
  {
    id: "C1_GRANTED_TAKES_IT_FOR_GRANTED",
    keyword: "GRANTED",
    operator: "take for granted",
    frames: "He {{gap}} that help will arrive",
    variants: ["TAKES IT FOR GRANTED"],
  },
  {
    id: "C1_RATHER_WOULD_RATHER_YOU",
    keyword: "RATHER",
    operator: "would rather",
    frames: "I {{gap}} share the ending yet",
    variants: ["WOULD RATHER YOU"],
    notes:
      'Preference construction that must be followed by a past-simple clause (e.g. "did not tell").',
  },
  {
    id: "C1_COME_COME_TO_A_DECISION",
    keyword: "COME",
    operator: "come to a decision",
    frames: "They finally {{gap}} on the offer",
    variants: ["COME TO A DECISION"],
  },
  {
    id: "C1_MISSED_HAD_MISSED_HER_FLIGHT",
    keyword: "MISSED",
    operator: "had missed her flight",
    frames: "If they {{gap}}, they would have contacted us",
    variants: ["HAD MISSED THEIR FLIGHT"],
    notes: "Full third conditional; keep the apodosis after the blank intact.",
  },
  {
    id: "C1_BRUSH_TO_BRUSH_UP_MY",
    keyword: "BRUSH",
    operator: "brush up on",
    frames: "My boss encouraged me to {{gap}} French",
    variants: ["BRUSH UP ON MY"],
    notes:
      "Keep the object pronoun after the blank so the cue supplies the phrasal core.",
  },
  {
    id: "C1_PICTURE_KEEPING_HER_IN_THE_PICTURE",
    keyword: "PICTURE",
    operator: "keep someone in the picture",
    frames: "She thanked me for {{gap}} about the situation",
    variants: ["KEEPING HER IN THE PICTURE", "KEEPING THEM IN THE PICTURE"],
    notes:
      'Encourage gerund after "for" plus indirect object pronoun within the blank.',
  },
  {
    id: "C1_SCARCELY_SCARCELY_HAD_THEY_LEFT",
    keyword: "SCARCELY",
    operator: "scarcely had ... when",
    frames: "{{gap}} when the storm began",
    variants: ["SCARCELY HAD THEY LEFT"],
    notes: "Requires inversion after negative adverbial.",
  },
  {
    id: "C1_HARDLY_HARDLY_HAD_WE_ARRIVED",
    keyword: "HARDLY",
    operator: "hardly had ... when",
    frames: "{{gap}} when the",
    variants: ["HARDLY HAD WE ARRIVED"],
  },
  {
    id: "C1_SOONER_NO_SOONER_HAD_THEY",
    keyword: "SOONER",
    operator: "no sooner ... than",
    frames: "{{gap}} than the",
    variants: ["NO SOONER HAD THEY LEFT"],
  },
  {
    id: "C1_LITTLE_LITTLE_DID_HE_KNOW",
    keyword: "LITTLE",
    operator: "little did ... know",
    frames: "{{gap}} the truth",
    variants: ["LITTLE DID HE KNOW"],
  },
  {
    id: "C1_ONLY_ONLY_WHEN_SHE_ARRIVED",
    keyword: "ONLY",
    operator: "only when ...",
    frames: "{{gap}} did she realise",
    variants: ["ONLY WHEN SHE ARRIVED"],
  },
  {
    id: "C1_UNDER_UNDER_NO_CIRCUMSTANCES",
    keyword: "UNDER",
    operator: "under no circumstances",
    frames: "{{gap}} you ignore safety rules",
    variants: ["UNDER NO CIRCUMSTANCES SHOULD"],
  },
  {
    id: "C1_RARELY_RARELY_DO_WE_SEE",
    keyword: "RARELY",
    operator: "rarely do ...",
    frames: "{{gap}} such dedication",
    variants: ["RARELY DO WE SEE"],
  },
  {
    id: "C1_NEVER_NEVER_HAVE_I_FELT",
    keyword: "NEVER",
    operator: "never have ...",
    frames: "{{gap}} so relieved",
    variants: ["NEVER HAVE I FELT"],
  },
  {
    id: "C1_ALLEGED_IS_ALLEGED_TO_HAVE",
    keyword: "ALLEGED",
    operator: "is alleged to have",
    frames: "The suspect {{gap}} stolen funds",
    variants: ["IS ALLEGED TO HAVE"],
  },
  {
    id: "C1_BELIEVED_IS_BELIEVED_TO_HAVE",
    keyword: "BELIEVED",
    operator: "is believed to have",
    frames: "The team {{gap}} lost the lead",
    variants: ["IS BELIEVED TO HAVE"],
  },
  {
    id: "C1_SAID_IS_SAID_TO_HAVE",
    keyword: "SAID",
    operator: "is said to have",
    frames: "He {{gap}} ignored the warnings",
    variants: ["IS SAID TO HAVE"],
  },
  {
    id: "C1_REPORTED_IS_REPORTED_TO_HAVE",
    keyword: "REPORTED",
    operator: "is reported to have",
    frames: "She {{gap}} resigned last week",
    variants: ["IS REPORTED TO HAVE"],
  },
  {
    id: "C1_THOUGHT_WAS_THOUGHT_TO_BE",
    keyword: "THOUGHT",
    operator: "was thought to be",
    frames: "The plan {{gap}} too risky",
    variants: ["WAS THOUGHT TO BE"],
  },
  {
    id: "C1_UNDERSTOOD_IS_UNDERSTOOD_TO_HAVE",
    keyword: "UNDERSTOOD",
    operator: "is understood to have",
    frames: "The company {{gap}} agreed in advance",
    variants: ["IS UNDERSTOOD TO HAVE"],
  },
  {
    id: "C1_RUMOURED_IS_RUMOURED_TO_BE",
    keyword: "RUMOURED",
    operator: "is rumoured to be",
    frames: "He {{gap}} considering a move",
    variants: ["IS RUMOURED TO BE"],
  },
  {
    id: "C1_SUPPOSED_IS_SUPPOSED_TO_HAVE",
    keyword: "SUPPOSED",
    operator: "is supposed to have",
    frames: "She {{gap}} completed the report",
    variants: ["IS SUPPOSED TO HAVE"],
  },
  {
    id: "C1_MEANT_IS_MEANT_TO_CONVEY",
    keyword: "MEANT",
    operator: "is meant to convey",
    frames: "The statement {{gap}} confidence",
    variants: ["IS MEANT TO CONVEY"],
  },
  {
    id: "C1_ATTENTION_DRAW_ATTENTION_TO",
    keyword: "ATTENTION",
    operator: "draw attention to",
    frames: "She {{gap}} the issue",
    variants: ["DRAW ATTENTION TO"],
  },
  {
    id: "C1_ADVANTAGE_TAKE_ADVANTAGE_OF",
    keyword: "ADVANTAGE",
    operator: "take advantage of",
    frames: "She {{gap}} the opportunity",
    variants: ["TAKE ADVANTAGE OF"],
  },
  {
    id: "C1_DISADVANTAGE_AT_A_DISADVANTAGE",
    keyword: "DISADVANTAGE",
    operator: "be at a disadvantage",
    frames: "{{gap}} in negotiations",
    variants: ["AT A DISADVANTAGE"],
  },
  {
    id: "C1_INTENTION_NO_INTENTION_OF",
    keyword: "INTENTION",
    operator: "have no intention of",
    frames: "He {{gap}} leaving early",
    variants: ["HAD NO INTENTION OF"],
  },
  {
    id: "C1_ABILITY_THE_ABILITY_TO",
    keyword: "ABILITY",
    operator: "have the ability to",
    frames: "She {{gap}} handle difficult clients",
    variants: ["HAD THE ABILITY TO"],
  },
  {
    id: "C1_POSSIBILITY_THE_POSSIBILITY_OF",
    keyword: "POSSIBILITY",
    operator: "raise the possibility of",
    frames: "They {{gap}} finding a solution",
    variants: ["RAISED THE POSSIBILITY OF"],
  },
  {
    id: "C1_LIKELIHOOD_THE_LIKELIHOOD_OF",
    keyword: "LIKELIHOOD",
    operator: "the likelihood of",
    frames: "We assessed {{gap}} rain tonight",
    variants: ["THE LIKELIHOOD OF"],
  },
  {
    id: "C1_PROBABILITY_THE_PROBABILITY_OF",
    keyword: "PROBABILITY",
    operator: "the probability of",
    frames: "Analysts {{gap}} recovery",
    variants: ["THE PROBABILITY OF"],
  },
  {
    id: "C1_RESPONSIBILITY_TAKE_RESPONSIBILITY_FOR",
    keyword: "RESPONSIBILITY",
    operator: "take responsibility for",
    frames: "They {{gap}} the error",
    variants: ["TAKE RESPONSIBILITY FOR"],
  },
  {
    id: "C1_IMPRESSION_GAVE_THE_IMPRESSION_THAT",
    keyword: "IMPRESSION",
    operator: "give the impression that",
    frames: "She {{gap}} he was interested",
    variants: ["GAVE THE IMPRESSION THAT"],
  },
  {
    id: "C1_OBJECTION_NO_OBJECTION_TO",
    keyword: "OBJECTION",
    operator: "raise an objection to",
    frames: "We {{gap}} paying extra",
    variants: ["RAISED NO OBJECTION TO"],
  },
  {
    id: "C1_CONSENT_GAVE_HIS_CONSENT_TO",
    keyword: "CONSENT",
    operator: "give consent to",
    frames: "He {{gap}} her request",
    variants: ["GAVE HIS CONSENT TO"],
  },
  {
    id: "C1_ACQUAINTED_BECOME_ACQUAINTED_WITH",
    keyword: "ACQUAINTED",
    operator: "become acquainted with",
    frames: "They {{gap}} new colleagues quickly",
    variants: ["BECOME ACQUAINTED WITH"],
  },
  {
    id: "C1_FAMILIAR_BECAME_FAMILIAR_WITH",
    keyword: "FAMILIAR",
    operator: "become familiar with",
    frames: "She {{gap}} the new platform",
    variants: ["BECAME FAMILIAR WITH"],
  },
  {
    id: "C1_OBJECTED_OBJECTED_TO_BEING",
    keyword: "OBJECTED",
    operator: "objected to being",
    frames: "They {{gap}} labelled incompetent",
    variants: ["OBJECTED TO BEING"],
  },
  {
    id: "C1_DEMANDED_DEMANDED_TO_KNOW",
    keyword: "DEMANDED",
    operator: "demand to know",
    frames: "{{gap}} behind the decision",
    variants: ["DEMANDED TO KNOW THE REASON"],
  },
  {
    id: "C1_PREVENT_PREVENT_THEM_FROM",
    keyword: "PREVENT",
    operator: "prevent someone from",
    frames: "The rules {{gap}} leaving early",
    variants: ["PREVENT THEM FROM"],
  },
  {
    id: "C1_RELUCTANT_WAS_RELUCTANT_TO",
    keyword: "RELUCTANT",
    operator: "be reluctant to",
    frames: "He {{gap}} share the news",
    variants: ["WAS RELUCTANT TO"],
  },
  {
    id: "C1_ESSENTIAL_IT_IS_ESSENTIAL_THAT",
    keyword: "ESSENTIAL",
    operator: "it is essential that",
    frames: "{{gap}} he attend",
    variants: ["IT IS ESSENTIAL THAT"],
  },
  {
    id: "C1_ADVISABLE_IT_IS_ADVISABLE_TO",
    keyword: "ADVISABLE",
    operator: "it is advisable to",
    frames: "{{gap}} consult a",
    variants: ["IT IS ADVISABLE TO"],
  },
  {
    id: "C1_SHOULD_SHOULD_HAVE_TOLD_ME",
    keyword: "SHOULD",
    operator: "should have + past participle",
    frames: "You {{gap}} earlier",
    variants: ["SHOULD HAVE TOLD ME"],
  },
  {
    id: "C1_OUGHT_OUGHT_TO_HAVE_WARNED",
    keyword: "OUGHT",
    operator: "ought to have + past participle",
    frames: "You {{gap}} her earlier",
    variants: ["OUGHT TO HAVE WARNED"],
  },
  {
    id: "C1_MIGHT_MIGHT_HAVE_FORGOTTEN_TO",
    keyword: "MIGHT",
    operator: "might have + past participle",
    frames: "They {{gap}} lock the door",
    variants: ["MIGHT HAVE FORGOTTEN TO"],
  },
  {
    id: "C1_COULD_COULD_HAVE_BEEN_AVOIDED",
    keyword: "COULD",
    operator: "could have been + past participle",
    frames: "The accident {{gap}} with better planning",
    variants: ["COULD HAVE BEEN AVOIDED"],
  },
  {
    id: "C1_MUST_MUST_HAVE_BEEN_EXHAUSTED",
    keyword: "MUST",
    operator: "must have been + adjective",
    frames: "He {{gap}} after the marathon",
    variants: ["MUST HAVE BEEN EXHAUSTED"],
  },
  {
    id: "C1_APOLOGY_MAKE_AN_APOLOGY_FOR",
    keyword: "APOLOGY",
    operator: "make an apology for",
    frames: "He {{gap}} arriving late",
    variants: ["MAKE AN APOLOGY FOR"],
  },
  {
    id: "C1_DIFFERENCE_MAKE_A_DIFFERENCE_TO",
    keyword: "DIFFERENCE",
    operator: "make a difference to",
    frames: "It {{gap}} the overall results",
    variants: [
      "MAKE A DIFFERENCE TO",
      "MAKE NO DIFFERENCE TO",
      "MAKE LITTLE DIFFERENCE TO",
    ],
    notes:
      "Allow both affirmative and negative determiner options per plan (“no/little difference”).",
  },
] as const;

const C2_CUE_DESCRIPTORS: readonly KeywordCueDescriptor[] = [
  {
    id: "C2_SOONER_NO_SOONER_HAD_THEY",
    keyword: "SOONER",
    operator: "no sooner ... than",
    frames: "{{gap}} than",
    variants: ["NO SOONER HAD THEY TAKEN THEIR SEATS"],
    notes: "Enforces inversion with paired than-clause.",
  },
  {
    id: "C2_HARDLY_HARDLY_HAD_SHE_ARRIVED",
    keyword: "HARDLY",
    operator: "hardly had ... when",
    frames: "{{gap}} when",
    variants: ["HARDLY HAD SHE ARRIVED"],
  },
  {
    id: "C2_CIRCUMSTANCES_UNDER_NO_CIRCUMSTANCES",
    keyword: "CIRCUMSTANCES",
    operator: "under no circumstances",
    frames: "{{gap}} they panic",
    variants: ["UNDER NO CIRCUMSTANCES SHOULD"],
  },
  {
    id: "C2_LITTLE_LITTLE_DID_THEY_IMAGINE",
    keyword: "LITTLE",
    operator: "little did ...",
    frames: "{{gap}} the consequences",
    variants: ["LITTLE DID THEY IMAGINE"],
  },
  {
    id: "C2_NOWHERE_NOWHERE_WAS_THE_REPORT",
    keyword: "NOWHERE",
    operator: "nowhere + inversion",
    frames: "{{gap}} to be found",
    variants: ["NOWHERE WAS THE REPORT"],
  },
  {
    id: "C2_ONLY_ONLY_WHEN_THE_RAIN",
    keyword: "ONLY",
    operator: "only when ...",
    frames: "{{gap}} did the crowd cheer",
    variants: ["ONLY WHEN THE RAIN STOPPED"],
  },
  {
    id: "C2_NOTWITHSTANDING_NOTWITHSTANDING_THE_DELAYS",
    keyword: "NOTWITHSTANDING",
    operator: "notwithstanding + noun",
    frames: "{{gap}}, the project finished",
    variants: ["NOTWITHSTANDING THE DELAYS"],
  },
  {
    id: "C2_ANYTHING_ANYTHING_BUT_SIMPLE",
    keyword: "ANYTHING",
    operator: "anything but",
    frames: "The task was {{gap}} to solve",
    variants: ["ANYTHING BUT SIMPLE"],
  },
  {
    id: "C2_VIRTUE_BY_VIRTUE_OF_HER",
    keyword: "VIRTUE",
    operator: "by virtue of",
    frames: "She succeeded {{gap}} leadership",
    variants: ["BY VIRTUE OF HER"],
  },
  {
    id: "C2_EVENT_IN_THE_EVENT_OF",
    keyword: "EVENT",
    operator: "in the event of",
    frames: "{{gap}} an outage",
    variants: ["IN THE EVENT OF"],
  },
  {
    id: "C2_MATTER_NO_MATTER_HOW_HARD",
    keyword: "MATTER",
    operator: "no matter how",
    frames: "{{gap}} you try",
    variants: ["NO MATTER HOW HARD"],
  },
  {
    id: "C2_MEANS_BY_NO_MEANS_WAS",
    keyword: "MEANS",
    operator: "by no means",
    frames: "{{gap}} the job easy",
    variants: ["BY NO MEANS WAS"],
  },
  {
    id: "C2_ACCOUNT_ON_NO_ACCOUNT_MUST",
    keyword: "ACCOUNT",
    operator: "on no account",
    frames: "{{gap}} you reveal the code",
    variants: ["ON NO ACCOUNT MUST"],
  },
  {
    id: "C2_POINT_AT_NO_POINT_DID",
    keyword: "POINT",
    operator: "at no point",
    frames: "{{gap}} he apologise",
    variants: ["AT NO POINT DID"],
  },
  {
    id: "C2_TIME_AT_NO_TIME_WAS",
    keyword: "TIME",
    operator: "at no time",
    frames: "{{gap}} safety compromised",
    variants: ["AT NO TIME WAS"],
  },
  {
    id: "C2_STAGE_AT_NO_STAGE_DID",
    keyword: "STAGE",
    operator: "at no stage",
    frames: "{{gap}} they admit fault",
    variants: ["AT NO STAGE DID"],
  },
  {
    id: "C2_LONG_SO_LONG_AS_YOU",
    keyword: "LONG",
    operator: "so long as",
    frames: "{{gap}} are honest",
    variants: ["SO LONG AS YOU"],
  },
  {
    id: "C2_HAD_HAD_IT_NOT_BEEN",
    keyword: "HAD",
    operator: "had it not been for",
    frames: "{{gap}} for her help, we would have failed",
    variants: ["HAD IT NOT BEEN"],
  },
  {
    id: "C2_WERE_WERE_IT_NOT_FOR",
    keyword: "WERE",
    operator: "were it not for",
    frames: "{{gap}} his advice, we would fail",
    variants: ["WERE IT NOT FOR"],
  },
  {
    id: "C2_LEST_LEST_THEY_SHOULD_FAIL",
    keyword: "LEST",
    operator: "lest + should + verb",
    frames: "{{gap}} again this year",
    variants: ["LEST THEY SHOULD FAIL"],
  },
  {
    id: "C2_SCARCELY_SCARCELY_HAD_THE_DOORS",
    keyword: "SCARCELY",
    operator: "scarcely had ... when",
    frames: "{{gap}} when",
    variants: ["SCARCELY HAD THE DOORS CLOSED"],
  },
  {
    id: "C2_WITHOUT_WITHOUT_SO_MUCH_AS",
    keyword: "WITHOUT",
    operator: "without so much as",
    frames: "{{gap}} a glance",
    variants: ["WITHOUT SO MUCH AS"],
  },
  {
    id: "C2_SHOULD_SHOULD_YOU_REQUIRE_FURTHER",
    keyword: "SHOULD",
    operator: "should you require ...",
    frames: "{{gap}} assistance",
    variants: ["SHOULD YOU REQUIRE FURTHER"],
  },
  {
    id: "C2_HAPPEN_SHOULD_IT_HAPPEN_THAT",
    keyword: "HAPPEN",
    operator: "should it happen that",
    frames: "{{gap}} the train is late",
    variants: ["SHOULD IT HAPPEN THAT"],
  },
  {
    id: "C2_ASSUMING_ASSUMING_THAT_THIS_HOLDS",
    keyword: "ASSUMING",
    operator: "assuming that ...",
    frames: "{{gap}}, we can proceed confidently",
    variants: ["ASSUMING THAT THIS HOLDS"],
  },
  {
    id: "C2_PROVIDED_PROVIDED_THAT_YOU_REMAIN",
    keyword: "PROVIDED",
    operator: "provided that ...",
    frames: "{{gap}} calm throughout the process",
    variants: ["PROVIDED THAT YOU REMAIN"],
  },
  {
    id: "C2_SEEING_SEEING_AS_HE_HAD",
    keyword: "SEEING",
    operator: "seeing as ...",
    frames: "{{gap}} promised to help",
    variants: ["SEEING AS HE HAD"],
  },
  {
    id: "C2_HAVING_HAVING_BEEN_INVITED_EARLY",
    keyword: "HAVING",
    operator: "having been + past participle",
    frames: "{{gap}} , she took her seat",
    variants: ["HAVING BEEN INVITED EARLY"],
  },
  {
    id: "C2_BEING_BEING_THE_ONLY_PERSON",
    keyword: "BEING",
    operator: "being the only ...",
    frames: "{{gap}} qualified for the role",
    variants: ["BEING THE ONLY PERSON"],
  },
  {
    id: "C2_DESPITE_DESPITE_HIS_HAVING_WON",
    keyword: "DESPITE",
    operator: "despite + perfect gerund",
    frames: "{{gap}} the championship before",
    variants: ["DESPITE HIS HAVING WON"],
  },
  {
    id: "C2_INSTEAD_INSTEAD_OF_GRANTING_THEM",
    keyword: "INSTEAD",
    operator: "instead of + gerund",
    frames: "{{gap}} the request, he delayed it",
    variants: ["INSTEAD OF GRANTING THEM"],
  },
  {
    id: "C2_BESIDES_BESIDES_BEING_HIGHLY_QUALIFIED",
    keyword: "BESIDES",
    operator: "besides being ...",
    frames: "{{gap}} , she is adaptable",
    variants: ["BESIDES BEING HIGHLY QUALIFIED"],
  },
  {
    id: "C2_REGARDLESS_REGARDLESS_OF_HOW_OFTEN",
    keyword: "REGARDLESS",
    operator: "regardless of how ...",
    frames: "{{gap}} they call",
    variants: ["REGARDLESS OF HOW OFTEN"],
  },
  {
    id: "C2_NEITHER_NEITHER_THE_DIRECTOR_NOR",
    keyword: "NEITHER",
    operator: "neither ... nor",
    frames: "{{gap}} accepted the proposal",
    variants: ["NEITHER THE DIRECTOR NOR THE STAFF"],
  },
  {
    id: "C2_NOR_NOR_DID_THEY_MENTION",
    keyword: "NOR",
    operator: "nor did ...",
    frames: "{{gap}} the leak",
    variants: ["NOR DID THEY MENTION"],
  },
  {
    id: "C2_WHATEVER_WHATEVER_HAPPENS_YOU_MUST",
    keyword: "WHATEVER",
    operator: "whatever happens ...",
    frames: "{{gap}} obey the rules",
    variants: ["WHATEVER HAPPENS YOU MUST"],
  },
  {
    id: "C2_WHOEVER_WHOEVER_IT_WAS_THAT",
    keyword: "WHOEVER",
    operator: "whoever it was that ...",
    frames: "{{gap}} broke the window should confess",
    variants: ["WHOEVER IT WAS THAT"],
  },
  {
    id: "C2_HOWEVER_HOWEVER_HARD_SHE_TRIED",
    keyword: "HOWEVER",
    operator: "however hard ...",
    frames: "{{gap}} she pushed, the door stayed shut",
    variants: ["HOWEVER HARD SHE TRIED"],
  },
  {
    id: "C2_WHEREVER_WHEREVER_HE_MAY_BE",
    keyword: "WHEREVER",
    operator: "wherever he may be",
    frames: "{{gap}} we will support him",
    variants: ["WHEREVER HE MAY BE"],
  },
  {
    id: "C2_WHENEVER_WHENEVER_YOU_MAY_NEED",
    keyword: "WHENEVER",
    operator: "whenever you may ...",
    frames: "{{gap}} assistance, call me immediately",
    variants: ["WHENEVER YOU MAY NEED"],
  },
  {
    id: "C2_BEYOND_BEYOND_ALL_EXPECTATIONS",
    keyword: "BEYOND",
    operator: "beyond all expectations",
    frames: "The outcome was {{gap}} for investors",
    variants: ["BEYOND ALL EXPECTATIONS"],
  },
  {
    id: "C2_NEVERTHELESS_NEVERTHELESS_HE_CONTINUED",
    keyword: "NEVERTHELESS",
    operator: "nevertheless + clause",
    frames: "{{gap}} working despite the setbacks",
    variants: ["NEVERTHELESS HE CONTINUED"],
  },
  {
    id: "C2_ALBEIT_ALBEIT_IN_A_LIMITED",
    keyword: "ALBEIT",
    operator: "albeit + phrase",
    frames: "{{gap}} capacity",
    variants: ["ALBEIT IN A LIMITED"],
  },
  {
    id: "C2_REGRETTABLY_REGRETTABLY_HE_FAILED_TO",
    keyword: "REGRETTABLY",
    operator: "regrettably + clause",
    frames: "{{gap}} submit the report on time",
    variants: ["REGRETTABLY HE FAILED TO"],
  },
  {
    id: "C2_OSTENSIBLY_OSTENSIBLY_TO_PROTECT_THEM",
    keyword: "OSTENSIBLY",
    operator: "ostensibly to + verb",
    frames: "{{gap}} the team",
    variants: ["OSTENSIBLY TO PROTECT"],
  },
  {
    id: "C2_INASMUCH_INASMUCH_AS_HE_FAILED",
    keyword: "INASMUCH",
    operator: "inasmuch as ...",
    frames: "{{gap}} to meet expectations",
    variants: ["INASMUCH AS HE FAILED"],
  },
  {
    id: "C2_NOTHING_NOTHING_SHORT_OF_MIRACULOUS",
    keyword: "NOTHING",
    operator: "nothing short of",
    frames: "{{gap}} miraculous",
    variants: ["NOTHING SHORT OF"],
  },
  {
    id: "C2_FAR_FAR_FROM_IDEAL_SITUATION",
    keyword: "FAR",
    operator: "far from + noun",
    frames: "{{gap}} for the team",
    variants: ["FAR FROM IDEAL"],
  },
  {
    id: "C2_SELDOM_SELDOM_IF_EVER_DOES",
    keyword: "SELDOM",
    operator: "seldom if ever",
    frames: "{{gap}} our coach raise his voice",
    variants: ["SELDOM IF EVER DOES"],
  },
  {
    id: "C2_MERELY_MERELY_BY_CHANCE_DID",
    keyword: "MERELY",
    operator: "merely by + noun",
    frames: "{{gap}} the plan succeed",
    variants: ["MERELY BY CHANCE DID"],
  },
  {
    id: "C2_BREACH_IN_BREACH_OF_THE",
    keyword: "BREACH",
    operator: "in breach of",
    frames: "He acted {{gap}} agreement",
    variants: ["IN BREACH OF THE"],
  },
  {
    id: "C2_GLIMPSE_CAUGHT_A_GLIMPSE_OF",
    keyword: "GLIMPSE",
    operator: "catch a glimpse of",
    frames: "They {{gap}} the comet",
    variants: ["CAUGHT A GLIMPSE OF"],
  },
  {
    id: "C2_SIGHT_CAUGHT_SIGHT_OF_HER",
    keyword: "SIGHT",
    operator: "catch sight of",
    frames: "They {{gap}} in the crowd",
    variants: ["CAUGHT SIGHT OF HER"],
  },
  {
    id: "C2_SIDES_NOT_TAKE_SIDES",
    keyword: "SIDES",
    operator: "not take sides",
    frames: "The chair must {{gap}} during the dispute",
    variants: ["NOT TAKE SIDES", "NOT TO TAKE SIDES"],
    notes:
      'Keeps the mediator impartial; allow optional "to" for reported guidance.',
  },
  {
    id: "C2_STAND_STAND_IN_FOR_HIM",
    keyword: "STAND",
    operator: "stand in for",
    frames: "Can you {{gap}} tomorrow evening",
    variants: ["STAND IN FOR HIM"],
  },
  {
    id: "C2_BRINK_ON_THE_BRINK_OF",
    keyword: "BRINK",
    operator: "on the brink of",
    frames: "The company is {{gap}} collapse",
    variants: ["ON THE BRINK OF"],
  },
  {
    id: "C2_WAY_MAKE_ONES_WAY",
    keyword: "WAY",
    operator: "make one's way",
    frames: "They {{gap}} through the crowds to the stage",
    variants: ["MADE THEIR WAY", "MADE HIS WAY", "MADE HER WAY"],
    notes:
      "Use past narrative framing; ensure possessive forms keep the apostrophe implicit via pronoun.",
  },
  {
    id: "C2_THREAT_BE_UNDER_THREAT",
    keyword: "THREAT",
    operator: "be under threat",
    frames: "is {{gap}} closure",
    variants: ["UNDER THREAT FROM", "UNDER THREAT OF"],
    notes:
      'Identifies existential risk phrasing; optional "of" when naming consequences.',
  },
  {
    id: "C2_VERGE_ON_THE_VERGE_OF",
    keyword: "VERGE",
    operator: "on the verge of",
    frames: "She is {{gap}} tears",
    variants: ["ON THE VERGE OF"],
  },
  {
    id: "C2_THRESHOLD_ON_THE_THRESHOLD_OF",
    keyword: "THRESHOLD",
    operator: "on the threshold of",
    frames: "The team is {{gap}} victory",
    variants: ["ON THE THRESHOLD OF"],
  },
  {
    id: "C2_HEIGHT_AT_THE_HEIGHT_OF",
    keyword: "HEIGHT",
    operator: "at the height of",
    frames: "The city was {{gap}} the tourist season",
    variants: ["AT THE HEIGHT OF"],
  },
  {
    id: "C2_DEPTHS_IN_THE_DEPTHS_OF",
    keyword: "DEPTHS",
    operator: "in the depths of",
    frames: "She was {{gap}} despair",
    variants: ["IN THE DEPTHS OF"],
  },
  {
    id: "C2_DISCUSSION_NOT_OPEN_TO_FURTHER_DISCUSSION",
    keyword: "DISCUSSION",
    operator: "not open to further discussion",
    frames: "is {{gap}} at this stage",
    variants: [
      "NOT OPEN TO FURTHER DISCUSSION",
      "NOT OPEN TO ANY FURTHER DISCUSSION",
    ],
    notes: "Signals finality; reinforce that negotiations have concluded.",
  },
] as const;

const B2_CUES = B2_CUE_DESCRIPTORS.map((descriptor) =>
  createCue("B2", descriptor)
);
const C1_CUES = C1_CUE_DESCRIPTORS.map((descriptor) =>
  createCue("C1", descriptor)
);
const C2_CUES = C2_CUE_DESCRIPTORS.map((descriptor) =>
  createCue("C2", descriptor)
);

export const keywordCueBankByLevel: Record<
  KeywordCueLevel,
  readonly KeywordCue[]
> = {
  B2: B2_CUES,
  C1: C1_CUES,
  C2: C2_CUES,
};

export function getKeywordCueBank(levelCode: string): readonly KeywordCue[] {
  const normalized = levelCode.trim().toUpperCase();
  if (normalized === "C2") {
    return keywordCueBankByLevel.C2;
  }
  if (normalized === "C1") {
    return keywordCueBankByLevel.C1;
  }
  return keywordCueBankByLevel.B2;
}
