begin;

-- Keep operational audit data outside every schema exposed by the Data API.
create schema if not exists private authorization postgres;

revoke all on schema private from public, anon, authenticated, service_role;

create table if not exists private.event_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null check (btrim(event_type) <> ''),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default clock_timestamp(),
  processed_at timestamptz
);

create index if not exists event_outbox_unprocessed_idx
  on private.event_outbox (created_at, id)
  where processed_at is null;

create table if not exists private.membership_alias_conflicts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  membership_id bigint references public.academy_memberships(id) on delete set null,
  email_login text not null,
  email_membership text not null,
  request_id uuid not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  detected_at timestamptz not null default clock_timestamp(),
  resolved_at timestamptz,
  resolver_id uuid references public.profiles(id) on delete set null,
  resolution_reason text,
  resolution_request_id uuid unique,
  constraint membership_alias_conflicts_login_email_check
    check (email_login = lower(btrim(email_login)) and position('@' in email_login) > 1),
  constraint membership_alias_conflicts_membership_email_check
    check (email_membership = lower(btrim(email_membership)) and position('@' in email_membership) > 1),
  constraint membership_alias_conflicts_request_key
    unique (email_login, email_membership, request_id)
);

create index if not exists membership_alias_conflicts_open_membership_idx
  on private.membership_alias_conflicts (membership_id, detected_at desc, id desc)
  where resolved_at is null;

create table if not exists private.membership_role_audit (
  id bigint generated by default as identity primary key,
  membership_id bigint references public.academy_memberships(id) on delete set null,
  academy_id bigint references public.academies(id) on delete set null,
  actor_user_id uuid references public.profiles(id) on delete set null,
  old_role text not null,
  new_role text not null,
  reason text,
  request_id uuid not null,
  cleaned_records jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp(),
  constraint membership_role_audit_request_key unique (request_id)
);

alter table private.event_outbox enable row level security;
alter table private.membership_alias_conflicts enable row level security;
alter table private.membership_role_audit enable row level security;

revoke all privileges on all tables in schema private
  from public, anon, authenticated, service_role;
revoke all privileges on all sequences in schema private
  from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema private
  revoke all on tables from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema private
  revoke all on sequences from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema private
  revoke execute on functions from public, anon, authenticated, service_role;

create or replace function private.assert_service_role()
returns void
language plpgsql
stable
security invoker
set search_path = ''
as $$
begin
  if coalesce(current_setting('role', true), '') <> 'service_role'
     and coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception using message = 'SERVICE_ROLE_REQUIRED';
  end if;
end;
$$;

create or replace function private.assert_admin_actor(
  p_actor_user_id uuid,
  p_actor_academy_id bigint,
  p_actor_is_platform_admin boolean,
  p_target_academy_id bigint
)
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.assert_service_role();

  if p_actor_user_id is null or p_target_academy_id is null then
    raise exception using message = 'ACTOR_CONTEXT_REQUIRED';
  end if;

  if p_actor_is_platform_admin then
    if not exists (
      select 1
      from public.profiles p
      where p.id = p_actor_user_id
        and p.role in ('platform_owner', 'super_admin')
    ) then
      raise exception using message = 'ACTOR_CONTEXT_REQUIRED';
    end if;
    return;
  end if;

  if p_actor_academy_id is null or p_actor_academy_id <> p_target_academy_id then
    raise exception using message = 'ROLE_SCOPE_CONFLICT';
  end if;

  if not exists (
    select 1
    from public.academy_memberships am
    where am.user_id = p_actor_user_id
      and am.academy_id = p_actor_academy_id
      and am.role = 'academy_admin'
      and am.status = 'active'
  ) then
    raise exception using message = 'ACTOR_CONTEXT_REQUIRED';
  end if;
end;
$$;

create or replace function public.enqueue_event_outbox(
  p_event_type text,
  p_payload jsonb
)
returns table (
  id bigint,
  event_type text,
  payload jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.assert_service_role();
  if p_event_type is null or btrim(p_event_type) = '' then
    raise exception using message = 'EVENT_TYPE_REQUIRED';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception using message = 'EVENT_PAYLOAD_INVALID';
  end if;

  return query
  insert into private.event_outbox (event_type, payload)
  values (btrim(p_event_type), p_payload)
  returning
    private.event_outbox.id,
    private.event_outbox.event_type,
    private.event_outbox.payload,
    private.event_outbox.created_at;
end;
$$;

create or replace function public.upsert_membership_alias_conflict(
  p_user_id uuid,
  p_membership_id bigint,
  p_email_login text,
  p_email_membership text,
  p_request_id uuid,
  p_payload jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  user_id uuid,
  email_login text,
  email_membership text,
  membership_id bigint,
  request_id uuid,
  payload jsonb,
  detected_at timestamptz,
  resolved_at timestamptz,
  resolver_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email_login text := lower(btrim(coalesce(p_email_login, '')));
  v_email_membership text := lower(btrim(coalesce(p_email_membership, '')));
begin
  perform private.assert_service_role();
  if position('@' in v_email_login) <= 1 or position('@' in v_email_membership) <= 1 then
    raise exception using message = 'ALIAS_EMAIL_INVALID';
  end if;
  if p_request_id is null then
    raise exception using message = 'REQUEST_ID_REQUIRED';
  end if;
  if p_user_id is not null and not exists (
    select 1 from public.profiles p where p.id = p_user_id
  ) then
    raise exception using message = 'ALIAS_USER_NOT_FOUND';
  end if;
  if p_membership_id is not null and not exists (
    select 1 from public.academy_memberships am where am.id = p_membership_id
  ) then
    raise exception using message = 'MEMBERSHIP_NOT_FOUND';
  end if;

  return query
  insert into private.membership_alias_conflicts (
    user_id,
    membership_id,
    email_login,
    email_membership,
    request_id,
    payload
  ) values (
    p_user_id,
    p_membership_id,
    v_email_login,
    v_email_membership,
    p_request_id,
    coalesce(p_payload, '{}'::jsonb)
  )
  on conflict on constraint membership_alias_conflicts_request_key do update set
    user_id = coalesce(excluded.user_id, private.membership_alias_conflicts.user_id),
    membership_id = coalesce(excluded.membership_id, private.membership_alias_conflicts.membership_id),
    payload = private.membership_alias_conflicts.payload || excluded.payload,
    resolved_at = null,
    resolver_id = null,
    resolution_reason = null,
    resolution_request_id = null
  returning
    private.membership_alias_conflicts.id,
    private.membership_alias_conflicts.user_id,
    private.membership_alias_conflicts.email_login,
    private.membership_alias_conflicts.email_membership,
    private.membership_alias_conflicts.membership_id,
    private.membership_alias_conflicts.request_id,
    private.membership_alias_conflicts.payload,
    private.membership_alias_conflicts.detected_at,
    private.membership_alias_conflicts.resolved_at,
    private.membership_alias_conflicts.resolver_id;
end;
$$;

create or replace function public.list_open_membership_alias_conflicts(
  p_membership_ids bigint[]
)
returns table (
  membership_id bigint,
  email_login text,
  email_membership text,
  detected_at timestamptz,
  resolved_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform private.assert_service_role();
  return query
  select distinct on (mac.membership_id)
    mac.membership_id,
    mac.email_login,
    mac.email_membership,
    mac.detected_at,
    mac.resolved_at
  from private.membership_alias_conflicts mac
  where mac.resolved_at is null
    and mac.membership_id = any(coalesce(p_membership_ids, '{}'::bigint[]))
  order by mac.membership_id, mac.detected_at desc, mac.id desc;
end;
$$;

create or replace function public.migrate_membership_role(
  p_actor_user_id uuid,
  p_actor_academy_id bigint,
  p_actor_is_platform_admin boolean,
  p_membership_id bigint,
  p_new_role text,
  p_reason text default null,
  p_request_id uuid default gen_random_uuid()
)
returns table (
  membership_id bigint,
  academy_id bigint,
  old_role text,
  new_role text,
  cleaned_records jsonb,
  metadata_payload jsonb,
  should_refresh_session boolean,
  request_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_membership public.academy_memberships%rowtype;
  v_profile_email text;
  v_conflicting_role text;
  v_student_profiles integer := 0;
  v_class_memberships integer := 0;
  v_cleaned jsonb;
  v_metadata_payload jsonb := null;
  v_metadata_request_id uuid := null;
  v_existing_audit private.membership_role_audit%rowtype;
  v_request_id uuid := coalesce(p_request_id, gen_random_uuid());
begin
  perform private.assert_service_role();
  if p_membership_id is null then
    raise exception using message = 'MEMBERSHIP_NOT_FOUND';
  end if;
  if p_new_role not in ('student', 'teacher') then
    raise exception using message = 'ROLE_IMMUTABLE';
  end if;

  select * into v_existing_audit
  from private.membership_role_audit mra
  where mra.request_id = v_request_id;

  if v_existing_audit.id is not null then
    if v_existing_audit.membership_id is distinct from p_membership_id
       or v_existing_audit.actor_user_id is distinct from p_actor_user_id
       or v_existing_audit.new_role is distinct from p_new_role then
      raise exception using message = 'REQUEST_ID_REUSE';
    end if;

    perform private.assert_admin_actor(
      p_actor_user_id,
      p_actor_academy_id,
      coalesce(p_actor_is_platform_admin, false),
      v_existing_audit.academy_id
    );

    select * into v_membership
    from public.academy_memberships am
    where am.id = p_membership_id;
    if v_membership.id is null then
      raise exception using message = 'MEMBERSHIP_NOT_FOUND';
    end if;

    if v_membership.user_id is not null then
      select synced.metadata_payload, synced.request_id
      into v_metadata_payload, v_metadata_request_id
      from public.sync_user_metadata(
        v_membership.user_id,
        '[]'::jsonb,
        v_request_id
      ) synced;
    end if;

    membership_id := v_existing_audit.membership_id;
    academy_id := v_existing_audit.academy_id;
    old_role := v_existing_audit.old_role;
    new_role := v_existing_audit.new_role;
    cleaned_records := v_existing_audit.cleaned_records;
    metadata_payload := v_metadata_payload;
    should_refresh_session := v_membership.user_id is not null;
    request_id := v_request_id;
    return next;
    return;
  end if;

  select * into v_membership
  from public.academy_memberships am
  where am.id = p_membership_id
  for update;
  if v_membership.id is null then
    raise exception using message = 'MEMBERSHIP_NOT_FOUND';
  end if;

  perform private.assert_admin_actor(
    p_actor_user_id,
    p_actor_academy_id,
    coalesce(p_actor_is_platform_admin, false),
    v_membership.academy_id
  );

  if v_membership.role = 'academy_admin' then
    raise exception using message = 'ROLE_IMMUTABLE';
  end if;

  if v_membership.user_id is not null then
    if exists (
      select 1
      from public.profiles p
      where p.id = v_membership.user_id
        and p.role in ('platform_owner', 'super_admin')
    ) or exists (
      select 1
      from public.academy_memberships am
      where am.user_id = v_membership.user_id
        and am.role = 'academy_admin'
        and am.id <> v_membership.id
    ) then
      raise exception using message = 'ROLE_IMMUTABLE_CROSS_ACADEMY';
    end if;

    select p.email into v_profile_email
    from public.profiles p
    where p.id = v_membership.user_id;
    if v_profile_email is null or lower(btrim(v_profile_email)) <> v_membership.email then
      raise exception using
        message = 'MEMBERSHIP_OWNERSHIP_CONFLICT',
        detail = format(
          'membership_id=%s user_id=%s email_login=%s email_membership=%s',
          v_membership.id,
          v_membership.user_id,
          coalesce(v_profile_email, 'unknown'),
          v_membership.email
        );
    end if;

    select am.role into v_conflicting_role
    from public.academy_memberships am
    where am.user_id = v_membership.user_id
      and am.id <> v_membership.id
      and am.status = 'active'
      and am.role <> p_new_role
    order by am.updated_at desc, am.id
    limit 1;
    if v_conflicting_role is not null then
      raise exception using
        message = 'ROLE_CONFLICT',
        detail = format('existing_role=%s new_role=%s', v_conflicting_role, p_new_role);
    end if;
  end if;

  if exists (
    select 1
    from private.membership_alias_conflicts mac
    where mac.membership_id = v_membership.id
      and mac.resolved_at is null
  ) then
    raise exception using
      message = 'MEMBERSHIP_OWNERSHIP_CONFLICT',
      detail = format(
        'membership_id=%s user_id=%s email_login=%s email_membership=%s',
        v_membership.id,
        coalesce(v_membership.user_id::text, 'unknown'),
        coalesce(v_profile_email, 'unknown'),
        v_membership.email
      );
  end if;

  if v_membership.role = 'student' and p_new_role = 'teacher' then
    delete from public.class_members cm where cm.membership_id = v_membership.id;
    get diagnostics v_class_memberships = row_count;
    delete from public.student_profiles sp where sp.membership_id = v_membership.id;
    get diagnostics v_student_profiles = row_count;
  end if;

  update public.academy_memberships am
  set role = p_new_role
  where am.id = v_membership.id;

  v_cleaned := jsonb_build_object(
    'student_profiles_archived', v_student_profiles,
    'class_memberships_removed', v_class_memberships
  );

  if v_membership.user_id is not null then
    perform public.reconcile_active_academy_preference(v_membership.user_id);
    select synced.metadata_payload, synced.request_id
    into v_metadata_payload, v_metadata_request_id
    from public.sync_user_metadata(
      v_membership.user_id,
      '[]'::jsonb,
      v_request_id
    ) synced;
  end if;

  insert into private.membership_role_audit (
    membership_id,
    academy_id,
    actor_user_id,
    old_role,
    new_role,
    reason,
    request_id,
    cleaned_records
  ) values (
    v_membership.id,
    v_membership.academy_id,
    p_actor_user_id,
    v_membership.role,
    p_new_role,
    nullif(btrim(coalesce(p_reason, '')), ''),
    v_request_id,
    v_cleaned
  )
  on conflict on constraint membership_role_audit_request_key do nothing;

  membership_id := v_membership.id;
  academy_id := v_membership.academy_id;
  old_role := v_membership.role;
  new_role := p_new_role;
  cleaned_records := v_cleaned;
  metadata_payload := v_metadata_payload;
  should_refresh_session := v_membership.user_id is not null;
  request_id := coalesce(v_metadata_request_id, v_request_id);
  return next;
end;
$$;

create or replace function public.resolve_membership_alias(
  p_actor_user_id uuid,
  p_actor_academy_id bigint,
  p_actor_is_platform_admin boolean,
  p_membership_id bigint,
  p_normalized_email text,
  p_reason text default null,
  p_request_id uuid default gen_random_uuid()
)
returns table (
  membership_id bigint,
  email_normalized text,
  metadata_payload jsonb,
  should_refresh_session boolean,
  request_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_membership public.academy_memberships%rowtype;
  v_conflict private.membership_alias_conflicts%rowtype;
  v_email text := lower(btrim(coalesce(p_normalized_email, '')));
  v_request_id uuid := coalesce(p_request_id, gen_random_uuid());
begin
  perform private.assert_service_role();
  if position('@' in v_email) <= 1 then
    raise exception using message = 'EMAIL_MISMATCH';
  end if;

  select * into v_membership
  from public.academy_memberships am
  where am.id = p_membership_id
  for update;
  if v_membership.id is null then
    raise exception using message = 'MEMBERSHIP_NOT_FOUND';
  end if;

  perform private.assert_admin_actor(
    p_actor_user_id,
    p_actor_academy_id,
    coalesce(p_actor_is_platform_admin, false),
    v_membership.academy_id
  );

  select * into v_conflict
  from private.membership_alias_conflicts mac
  where mac.membership_id = v_membership.id
    and mac.resolution_request_id = v_request_id
  order by mac.resolved_at desc, mac.id desc
  limit 1;

  if v_conflict.id is not null
     and v_conflict.email_login = v_email
     and v_membership.email = v_email then
    membership_id := v_membership.id;
    email_normalized := v_email;
    metadata_payload := null;
    should_refresh_session := false;
    request_id := v_request_id;
    return next;
    return;
  end if;
  if v_conflict.id is not null then
    raise exception using message = 'REQUEST_ID_REUSE';
  end if;

  if v_membership.status <> 'awaiting_login' or v_membership.user_id is not null then
    raise exception using message = 'INVALID_MEMBERSHIP_STATUS';
  end if;

  select * into v_conflict
  from private.membership_alias_conflicts mac
  where mac.membership_id = v_membership.id
    and mac.resolved_at is null
  order by mac.detected_at desc, mac.id desc
  limit 1
  for update;

  if v_conflict.id is null or v_conflict.email_login <> v_email then
    raise exception using message = 'EMAIL_MISMATCH';
  end if;

  begin
    update public.academy_memberships am
    set email = v_email
    where am.id = v_membership.id;
  exception
    when unique_violation then
      raise exception using message = 'EMAIL_MISMATCH';
  end;

  update private.membership_alias_conflicts mac
  set resolved_at = clock_timestamp(),
      resolver_id = p_actor_user_id,
      resolution_reason = nullif(btrim(coalesce(p_reason, '')), ''),
      resolution_request_id = v_request_id
  where mac.id = v_conflict.id;

  update private.membership_alias_conflicts mac
  set resolved_at = clock_timestamp(),
      resolver_id = p_actor_user_id,
      resolution_reason = nullif(btrim(coalesce(p_reason, '')), '')
  where mac.membership_id = v_membership.id
    and mac.resolved_at is null
    and mac.id <> v_conflict.id;

  membership_id := v_membership.id;
  email_normalized := v_email;
  metadata_payload := null;
  should_refresh_session := false;
  request_id := v_request_id;
  return next;
end;
$$;

create or replace function public.create_speaking_session(
  p_persona_id bigint,
  p_scenario_id bigint default null,
  p_use_profile boolean default false,
  p_nuances text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_membership public.academy_memberships%rowtype;
  v_session_id uuid;
begin
  select * into v_membership from public.resolve_current_membership(auth.uid());
  if v_membership.id is null
     or v_membership.status <> 'active'
     or v_membership.role <> 'student' then
    raise exception 'Active student membership required';
  end if;
  if not exists (
    select 1 from public.speaking_personas sp where sp.id = p_persona_id and sp.is_active
  ) then
    raise exception 'Persona not available';
  end if;
  if p_scenario_id is not null and not exists (
    select 1 from public.speaking_scenarios ss
    where ss.id = p_scenario_id
      and (
        ss.created_by_membership_id is null
        or ss.created_by_membership_id = v_membership.id
      )
  ) then
    raise exception 'Scenario not accessible';
  end if;

  insert into public.speaking_sessions (
    membership_id, scenario_id, persona_id, use_profile, nuances
  ) values (
    v_membership.id, p_scenario_id, p_persona_id, p_use_profile, nullif(btrim(p_nuances), '')
  ) returning id into v_session_id;
  return v_session_id;
end;
$$;

drop policy if exists speaking_sessions_insert on public.speaking_sessions;
drop policy if exists speaking_sessions_update on public.speaking_sessions;
drop policy if exists speaking_sessions_delete on public.speaking_sessions;
create policy speaking_sessions_insert on public.speaking_sessions
  for insert to authenticated
  with check (
    exists (
      select 1 from public.academy_memberships am
      where am.id = speaking_sessions.membership_id
        and am.user_id = auth.uid()
        and am.status = 'active'
        and am.role = 'student'
    )
  );
create policy speaking_sessions_update on public.speaking_sessions
  for update to authenticated
  using (
    exists (
      select 1 from public.academy_memberships am
      where am.id = speaking_sessions.membership_id
        and am.user_id = auth.uid()
        and am.status = 'active'
        and am.role = 'student'
    )
  )
  with check (
    exists (
      select 1 from public.academy_memberships am
      where am.id = speaking_sessions.membership_id
        and am.user_id = auth.uid()
        and am.status = 'active'
        and am.role = 'student'
    )
  );
create policy speaking_sessions_delete on public.speaking_sessions
  for delete to authenticated
  using (
    exists (
      select 1 from public.academy_memberships am
      where am.id = speaking_sessions.membership_id
        and am.user_id = auth.uid()
        and am.status = 'active'
        and am.role = 'student'
    )
  );

-- These mutations are orchestrated by Edge Functions after their actor checks.
-- Database grants and runtime checks both require service_role.
create or replace function public.admin_prepare_membership_invite(
  p_academy_id bigint,
  p_email text,
  p_role text default 'student'
)
returns public.academy_memberships
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(btrim(p_email));
  v_membership public.academy_memberships%rowtype;
begin
  perform private.assert_service_role();
  if p_role not in ('student', 'teacher', 'academy_admin') then
    raise exception 'Invalid role';
  end if;
  if position('@' in v_email) <= 1 then
    raise exception 'Invalid email';
  end if;

  insert into public.academy_memberships (academy_id, email, role, status)
  values (p_academy_id, v_email, p_role, 'awaiting_login')
  on conflict (academy_id, email) do update set
    role = excluded.role,
    status = case
      when public.academy_memberships.user_id is null then 'awaiting_login'
      else public.academy_memberships.status
    end
  returning * into v_membership;
  return v_membership;
end;
$$;

create or replace function public.update_membership_subscription_dates(
  p_membership_id bigint,
  p_subscription_start_date date default null,
  p_subscription_end_date date default null,
  p_clear_subscription_start boolean default false,
  p_clear_subscription_end boolean default false,
  p_request_id uuid default gen_random_uuid()
)
returns table (
  academy_id bigint,
  created_at timestamptz,
  email text,
  id bigint,
  metadata_payload jsonb,
  metadata_targets jsonb,
  request_id uuid,
  role text,
  should_refresh_session boolean,
  status text,
  subscription_end_date date,
  subscription_start_date date,
  updated_at timestamptz,
  user_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_membership public.academy_memberships%rowtype;
  v_metadata_payload jsonb := null;
  v_metadata_request_id uuid := null;
begin
  perform private.assert_service_role();
  select * into v_membership
  from public.academy_memberships am where am.id = p_membership_id for update;
  if v_membership.id is null then
    raise exception 'Not authorized';
  end if;

  update public.academy_memberships am
  set subscription_start_date = case
        when p_clear_subscription_start then null
        else coalesce(p_subscription_start_date, am.subscription_start_date)
      end,
      subscription_end_date = case
        when p_clear_subscription_end then null
        else coalesce(p_subscription_end_date, am.subscription_end_date)
      end
  where am.id = p_membership_id
  returning * into v_membership;

  if v_membership.user_id is not null then
    select synced.metadata_payload, synced.request_id
    into v_metadata_payload, v_metadata_request_id
    from public.sync_user_metadata(
      v_membership.user_id,
      '[]'::jsonb,
      p_request_id
    ) synced;
  end if;

  academy_id := v_membership.academy_id;
  created_at := v_membership.created_at;
  email := v_membership.email;
  id := v_membership.id;
  metadata_payload := v_metadata_payload;
  metadata_targets := case
    when v_membership.user_id is null then '[]'::jsonb
    else jsonb_build_array(v_membership.user_id)
  end;
  request_id := coalesce(v_metadata_request_id, p_request_id, gen_random_uuid());
  role := v_membership.role;
  should_refresh_session := v_membership.user_id is not null;
  status := v_membership.status;
  subscription_end_date := v_membership.subscription_end_date;
  subscription_start_date := v_membership.subscription_start_date;
  updated_at := v_membership.updated_at;
  user_id := v_membership.user_id;
  return next;
end;
$$;

create or replace function public.admin_manage_membership(
  p_membership_id bigint,
  p_target_user_id uuid default null,
  p_email text default null,
  p_role text default null,
  p_subscription_start_date date default null,
  p_subscription_end_date date default null,
  p_clear_user boolean default false,
  p_delete_auth_user boolean default false,
  p_allow_active_clear boolean default false,
  p_status text default null,
  p_force_status_active boolean default false,
  p_request_id uuid default gen_random_uuid()
)
returns table (
  academy_id bigint,
  created_at timestamptz,
  email text,
  id bigint,
  metadata_payload jsonb,
  metadata_targets jsonb,
  request_id uuid,
  role text,
  should_refresh_session boolean,
  status text,
  subscription_end_date date,
  subscription_start_date date,
  updated_at timestamptz,
  user_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_membership public.academy_memberships%rowtype;
  v_old_user_id uuid;
  v_old_metadata_payload jsonb;
  v_new_metadata_payload jsonb;
  v_metadata_targets jsonb := '[]'::jsonb;
  v_request_id uuid := coalesce(p_request_id, gen_random_uuid());
begin
  perform private.assert_service_role();
  select * into v_membership
  from public.academy_memberships am where am.id = p_membership_id for update;
  if v_membership.id is null then
    raise exception 'Not authorized';
  end if;
  if p_delete_auth_user then
    raise exception using message = 'AUTH_USER_DELETE_UNSUPPORTED';
  end if;
  if p_role is not null and p_role not in ('student', 'teacher', 'academy_admin') then
    raise exception 'Invalid role';
  end if;
  if p_status is not null and p_status not in ('awaiting_login', 'active', 'inactive') then
    raise exception 'Invalid status';
  end if;
  if p_clear_user and v_membership.status = 'active' and not p_allow_active_clear then
    raise exception 'Explicit active-clear approval is required';
  end if;

  v_old_user_id := v_membership.user_id;
  update public.academy_memberships am
  set user_id = case when p_clear_user then null else coalesce(p_target_user_id, am.user_id) end,
      email = coalesce(lower(btrim(p_email)), am.email),
      role = coalesce(p_role, am.role),
      status = case
        when p_clear_user then 'awaiting_login'
        when p_force_status_active then 'active'
        else coalesce(p_status, am.status)
      end,
      subscription_start_date = coalesce(p_subscription_start_date, am.subscription_start_date),
      subscription_end_date = coalesce(p_subscription_end_date, am.subscription_end_date)
  where am.id = p_membership_id
  returning * into v_membership;

  if v_old_user_id is not null then
    perform public.reconcile_active_academy_preference(v_old_user_id);
    select synced.metadata_payload into v_old_metadata_payload
    from public.sync_user_metadata(
      v_old_user_id,
      '[]'::jsonb,
      v_request_id
    ) synced;
    v_metadata_targets := v_metadata_targets || jsonb_build_array(
      jsonb_build_object(
        'user_id', v_old_user_id,
        'metadata_payload', v_old_metadata_payload,
        'should_refresh_session', true,
        'request_id', v_request_id
      )
    );
  end if;
  if v_membership.user_id is not null
     and v_membership.user_id is distinct from v_old_user_id then
    perform public.reconcile_active_academy_preference(v_membership.user_id);
    select synced.metadata_payload into v_new_metadata_payload
    from public.sync_user_metadata(
      v_membership.user_id,
      '[]'::jsonb,
      v_request_id
    ) synced;
    v_metadata_targets := v_metadata_targets || jsonb_build_array(
      jsonb_build_object(
        'user_id', v_membership.user_id,
        'metadata_payload', v_new_metadata_payload,
        'should_refresh_session', true,
        'request_id', v_request_id
      )
    );
  end if;

  academy_id := v_membership.academy_id;
  created_at := v_membership.created_at;
  email := v_membership.email;
  id := v_membership.id;
  metadata_payload := case
    when v_membership.user_id is null then v_old_metadata_payload
    when v_membership.user_id = v_old_user_id then v_old_metadata_payload
    else v_new_metadata_payload
  end;
  metadata_targets := v_metadata_targets;
  request_id := v_request_id;
  role := v_membership.role;
  should_refresh_session := jsonb_array_length(v_metadata_targets) > 0;
  status := v_membership.status;
  subscription_end_date := v_membership.subscription_end_date;
  subscription_start_date := v_membership.subscription_start_date;
  updated_at := v_membership.updated_at;
  user_id := v_membership.user_id;
  return next;
end;
$$;

create or replace function public.update_profile_membership_data(
  p_membership_id bigint,
  p_role text default null,
  p_membership_status text default null,
  p_academy_id bigint default null,
  p_request_id uuid default gen_random_uuid()
)
returns table (
  academy_id bigint,
  created_at timestamptz,
  email text,
  id bigint,
  metadata_payload jsonb,
  metadata_targets jsonb,
  request_id uuid,
  role text,
  should_refresh_session boolean,
  status text,
  subscription_end_date date,
  subscription_start_date date,
  updated_at timestamptz,
  user_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.assert_service_role();
  return query
  select * from public.admin_manage_membership(
    p_membership_id => p_membership_id,
    p_role => p_role,
    p_status => p_membership_status,
    p_request_id => p_request_id
  );
end;
$$;

revoke all privileges on function private.assert_service_role()
  from public, anon, authenticated, service_role;
revoke all privileges on function private.assert_admin_actor(uuid, bigint, boolean, bigint)
  from public, anon, authenticated, service_role;

revoke all privileges on function public.enqueue_event_outbox(text, jsonb)
  from public, anon, authenticated;
revoke all privileges on function public.upsert_membership_alias_conflict(uuid, bigint, text, text, uuid, jsonb)
  from public, anon, authenticated;
revoke all privileges on function public.list_open_membership_alias_conflicts(bigint[])
  from public, anon, authenticated;
revoke all privileges on function public.migrate_membership_role(uuid, bigint, boolean, bigint, text, text, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.resolve_membership_alias(uuid, bigint, boolean, bigint, text, text, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.update_profile_membership_data(bigint, text, text, bigint, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.admin_prepare_membership_invite(bigint, text, text)
  from public, anon, authenticated;
revoke all privileges on function public.update_membership_subscription_dates(bigint, date, date, boolean, boolean, uuid)
  from public, anon, authenticated;
revoke all privileges on function public.admin_manage_membership(bigint, uuid, text, text, date, date, boolean, boolean, boolean, text, boolean, uuid)
  from public, anon, authenticated;

grant execute on function public.enqueue_event_outbox(text, jsonb) to service_role;
grant execute on function public.upsert_membership_alias_conflict(uuid, bigint, text, text, uuid, jsonb) to service_role;
grant execute on function public.list_open_membership_alias_conflicts(bigint[]) to service_role;
grant execute on function public.migrate_membership_role(uuid, bigint, boolean, bigint, text, text, uuid) to service_role;
grant execute on function public.resolve_membership_alias(uuid, bigint, boolean, bigint, text, text, uuid) to service_role;
grant execute on function public.update_profile_membership_data(bigint, text, text, bigint, uuid)
  to service_role;

grant execute on function public.admin_prepare_membership_invite(bigint, text, text)
  to service_role;
grant execute on function public.update_membership_subscription_dates(bigint, date, date, boolean, boolean, uuid)
  to service_role;
grant execute on function public.admin_manage_membership(bigint, uuid, text, text, date, date, boolean, boolean, boolean, text, boolean, uuid)
  to service_role;

comment on function public.create_speaking_session(bigint, bigint, boolean, text) is
  'Creates a speaking session only for the authenticated user''s active student membership.';
comment on function public.admin_prepare_membership_invite(bigint, text, text) is
  'Service-role-only Edge orchestration RPC for preparing membership invitations.';
comment on function public.update_membership_subscription_dates(bigint, date, date, boolean, boolean, uuid) is
  'Service-role-only Edge orchestration RPC for membership subscription dates.';
comment on function public.admin_manage_membership(bigint, uuid, text, text, date, date, boolean, boolean, boolean, text, boolean, uuid) is
  'Service-role-only Edge orchestration RPC for privileged membership mutation.';

commit;
